### ISSUE TITLE
Playlist sort

### ISSUE THREAD

**Issue by souza-victor** [polymorphicshade/NewPipe#105]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
I'd like to have the option to _rearrange playlists in normal order and in inverse order_. That's it. 

#### Why do you want this feature?
Because adding videos is easier if a playlist is in chronological order ascending (since it adds to the end of the playlist), but then when you play the playlist you'd usually want to watch the newer one first. This could be accomplished simply by adding a Add to top of playlist action in the pop up menu, or by adding a pop up that asks where you'd like to insert the video to the original Add to playlist. However, if you've watched all the new videos, then you want to sort it again, ascending, so that videos that are supposed to be watched one after the other will have context.

**Comment by souza-victor** [comment]
> Please fill out our template. If you did, you would've noticed that this is not the place for your issue.

I thought that _was_ the template. The CONTRIBUTING file does not link to a different template. I did find it by browsing so I'll include in the original post ASAP.

**Comment by Atemu** [comment]
The template is pre-filled when you file an issue.

**Comment by souza-victor** [comment]
> The template is pre-filled when you file an issue.

So I guess I found a bug. I thought it could be because I used a mobile phone to open the issue, but I tried again and it did show the templates. But then I remember that I had been logged out when I clicked the New issue button. And here's the kicker:

If you are in the issues page in a mobile phone, logged out, click the New issue button, click log in, then login, the New issue page will appear without any mention to templates.

I was just able to reproduce this using Edge (Chromium), opening an anonymous window, turning on Dev Tools, and using the mobile emulator to run the steps above.

**Comment by SameenAhnaf** [comment]
>The template is pre-filled when you file an issue.

@Atemu As no label is automatically added, it can be expected that the user didn't see the template while opening the issue.

**Comment by xorbital** [comment]
> > The template is pre-filled when you file an issue.
> 
> So I guess I found a bug. I thought it could be because I used a mobile phone to open the issue, but I tried again and it did show the templates. But then I remember that I had been logged out when I clicked the New issue button. And here's the kicker:
> 
> If you are in the issues page in a mobile phone, logged out, when you click the New issue button, then click log in in the pop up, then login, the New issue page will appear, empty, without any mention to templates.
> 
> I was just able to reproduce this using Edge (Chromium), opening an anonymous window, turning on Dev Tools, and using the mobile emulator to run the steps above.

That's probably [this issue](https://github.com/github/feedback/discussions/4696) on GitHub, you could upvote that since you were affected by it.

As for the playlist sorting: This fork is explicitly only for adding sponsorblock functionality:
> This feature is related to sponsor or ad blocking and/or has explicitly been rejected upstream. This is not the place for stale upstream feature requests

Also it seems like there are already issues open upstream: TeamNewPipe/NewPipe#5237 TeamNewPipe/NewPipe#7326

**Comment by polymorphicshade** [comment]
Closing because this feature should first be requested upstream.
