### ISSUE TITLE
Can't import subscription JSON file from one device to another

### ISSUE THREAD

**Issue by HairyMilkshakes** [polymorphicshade/NewPipe#109]
### Checklist

- [x] I am using the latest version - 0.21.13 

### Steps to reproduce the bug

1. Export .json file from another device with Newpipe Sponsorblock installed
2. Attempt to import from previous export on second device
3. JSON file is greyed out and cannot be imported.

### Actual behavior

Should be explanatory in the steps to reproduce bug.

### Expected behavior

Expecting the JSON file to be accepted.

### Screenshots/Screen recordings

![2021-11-06_09-52-08](https://user-images.githubusercontent.com/13473043/140617508-1e84586d-685d-4a82-a703-04fc8813bc3c.png)

### Device info

 - Android version/Custom ROM version: Android 9
 - Device model: Note8

**Comment by Atemu** [comment]
Please use the issue template.

**Comment by xorbital** [comment]
This is probably an [upstream issue](https://github.com/TeamNewPipe/NewPipe/issues/7326), since this fork doesn't really touch subscriptions.

**Comment by polymorphicshade** [comment]
Closing because this feature should first be requested upstream.
