### ISSUE TITLE
How do I stay up to date?

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [polymorphicshade/NewPipe#110]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?

I would like to stay as minimalistic as possible. I currently have F-droid where I get all my updates from. How can I make sure this app stays updated almost on every relase? Is there an F-droid repo planned? Do I have to install IzzyDroid? How quick an updated version from the main repo get forked, then be available here after the new release? I observed that the versions released here are a bit inconsistent. Does this mean updating this fork is done in a manual way and the availability depends on how quick the maintainer is?

**Comment by xorbital** [comment]
If you've enabled the Setting, you'll get a notification once a new release is out. Tapping on that notification will download the new .apk
Alternatively, you can hit "Watch" here on GitHub - Custom - Releases, you'll then receive an e-mail once a new release is out.

**Comment by IHateTheProgrammingClass** [comment]
@xorbital And that button is modified to download the forked release .apk correct?

**Comment by xorbital** [comment]
Yes, it its, I've updated this way multiple times :)
