### ISSUE TITLE
Implement new SponsorBlock Category Filler Tangent

### ISSUE THREAD

**Issue by xorbital** [polymorphicshade/NewPipe#111]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This feature is related to sponsor or ad blocking and/or has explicitly been rejected upstream. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

SponsorBlock supports new categories, including `Preview/Recap`, `Highlight` (both tracked in #99) and `Filler Tangent`.

#### Why do you want this feature?

To stay in sync with upstream

**Comment by Relected** [comment]
I agree with this one

**Comment by MDP43140** [comment]
@Relected same, i will make a PR implementing filler category
