### ISSUE TITLE
Error and crash on playing long videos

### ISSUE THREAD

**Issue by thealex626** [polymorphicshade/NewPipe#112]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [ ] This issue CANNOT be reproduced with the same version of upstream NewPipe 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open any few hours-long video (like 8 hours long audio books)

### Actual behavior

1. The app will stuck with infinite loading
2. Upon retrying, the app crashes with the error reporting window.

### Logs

{"user_action":"ui error","request":"ACRA report","content_language":"ru-RU","content_country":"RU","app_language":"ru_RU","service":"none","package":"org.polymorphicshade.newpipe","version":"0.21.13","os":"Linux Android 5.0.2 - 21","time":"2021-11-22 20:00","exceptions":["java.lang.OutOfMemoryError: Failed to allocate a 1048588 byte allocation with 317054 free bytes and 309KB until OOM\n\tat dalvik.system.VMRuntime.newNonMovableArray(Native Method)\n\tat android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)\n\tat android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:827)\n\tat android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:646)\n\tat android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1019)\n\tat android.content.res.Resources.loadDrawableForCookie(Resources.java:3778)\n\tat android.content.res.Resources.loadDrawable(Resources.java:3651)\n\tat android.content.res.Resources.getDrawable(Resources.java:1865)\n\tat android.content.Context.getDrawable(Context.java:408)\n\tat androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java:862)\n\tat androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:480)\n\tat androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:147)\n\tat androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:135)\n\tat androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)\n\tat androidx.appcompat.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:90)\n\tat androidx.appcompat.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:98)\n\tat org.schabi.newpipe.MainActivity.onResume(MainActivity.java:495)\n\tat android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)\n\tat android.app.Activity.performResume(Activity.java:6495)\n\tat android.app.ActivityThread.performNewIntents(ActivityThread.java:2961)\n\tat android.app.ActivityThread.handleNewIntent(ActivityThread.java:2968)\n\tat android.app.ActivityThread.access$1700(ActivityThread.java:181)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1554)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:145)\n\tat android.app.ActivityThread.main(ActivityThread.java:6145)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat java.lang.reflect.Method.invoke(Method.java:372)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)\n"],"user_comment":""}

### Device info

 - Android version/Custom ROM version: 5.0.2
 - Device model: Samsung Galaxy A3 (2015)

**Comment by polymorphicshade** [comment]
Closed because this crash has nothing to do with my fork.
