### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by brnwlshubh** [polymorphicshade/NewPipe#115]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] This feature is related to sponsor or ad blocking and/or has explicitly been rejected upstream. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Can you please include this https://github.com/TeamNewPipe/NewPipe/issues/5445 in your Newpipe Repo.

Thanks in advance.

**Comment by polymorphicshade** [comment]
I have no plans to implement something like this, but if someone else does I'll be happy to merge in their changes.
