### ISSUE TITLE
Landscape Bug Android 12 / Pixel Phones

### ISSUE THREAD

**Issue by Fexiven** [polymorphicshade/NewPipe#116]
Hey, could you please update the ExoPlayer to version 2.14.2 like [here](https://github.com/TeamNewPipe/NewPipe/pull/7005) 
There's a landscape resizing bug on Android 12
In my case on the Pixel 6
![Screenshot_20211214-005622](https://user-images.githubusercontent.com/48439988/145907864-3eaa0a52-0280-4aa8-9765-5a15533cb350.png)

**Comment by Atemu** [comment]
Fixed in https://github.com/polymorphicshade/NewPipe/releases/tag/v0.21.14

**Comment by Fexiven** [comment]
Hmmm, I already have that version, the bug still exist

**Comment by polymorphicshade** [comment]
Closed due to this issue not being specific to my fork.
