### ISSUE TITLE
Ability to set a blank Page as the homepage like in NewPipe.

### ISSUE THREAD

**Issue by Mesum-Hussain** [polymorphicshade/NewPipe#119]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This feature is related to sponsor or ad blocking and/or has explicitly been rejected upstream. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

There is a feature in NewPipe for removing the trending, and other tabs and all the homepage feeds and replacing everything with just a a blank page. I was using that in NewPipe for getting de-addicted from watching mindless videos. Then I got to know about this fork and immediately switched to it as an old Vanced user.
But I am missing that feature of NewPipe to get rid of all the homepage feeds and replacing everything with just a blank page.

Please update this app with the latest changes in new pipe in order to get that feature. 

Thank you.

#### Why do you want this feature?

It would help me get de-addicted from watching mindless video.

**Comment by Atemu** [comment]
That feature has been in NP and NP Sponsorblock for a long time already: Settings -> Content -> Content of main page

**Comment by Mesum-Hussain** [comment]
> That feature has been in NP and NP Sponsorblock for a long time already: Settings -> Content -> Content of main page

Sorry my bad. Thank you.
