### ISSUE TITLE
Any plans for rebranding the app?

### ISSUE THREAD

**Issue by Mesum-Hussain** [polymorphicshade/NewPipe#120]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
Are the mainteners planning to change the name of the app anytime soon? It's getting a little difficult to find this repo because of the same name as NewPipe (it's getting disappeared in the shadow of NewPipe). I think this project should grow as an individual project and stop remaining a fork of NewPipe. It should be rebranded and redesigned to get its own personality. Would love to know the opinion of the maintainers.

I can help with design ideas if needed.

**Comment by Atemu** [comment]
https://github.com/polymorphicshade/NewPipe/issues/12
