### ISSUE TITLE
Swipe up to open Fullscreen mode

### ISSUE THREAD

**Issue by pc00per** [polymorphicshade/NewPipe#121]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] This feature is related to sponsor or ad blocking and/or has explicitly been rejected upstream. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

TeamNewPipe#7624

#### Why do you want this feature?

TeamNewPipe#7624

**Comment by Atemu** [comment]
Read the issue template.

**Comment by polymorphicshade** [comment]
Closing because this feature should first be requested upstream.
