### ISSUE TITLE
Channel groups in subscription backup export

### ISSUE THREAD

**Issue by pc00per** [polymorphicshade/NewPipe#122]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] This feature is related to sponsor or ad blocking and/or has explicitly been rejected upstream. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

TeamNewPipe#7625

#### Why do you want this feature?

TeamNewPipe#7625

**Comment by polymorphicshade** [comment]
This is better done upstream.
