### ISSUE TITLE
Add integration with returnyoutubedislike.com

### ISSUE THREAD

**Issue by tr7zw** [polymorphicshade/NewPipe#125]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] ~~This feature is related to sponsor or ad blocking and/or~~ has explicitly been rejected upstream. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Using the ``https://returnyoutubedislikeapi.com/votes?videoId=`` endpoint, basic dislike counts can be restored. 
Upstream this request is open since November 30th and seems like it won't make it to NewPipe because the database and backend aren't open source.

#### Why do you want this feature?

Dislikes are an important part of youtube, and there is currently no good way to get them back on mobile(especially in combination with sponsorblock).

**Comment by Fehertukor** [comment]
Please @polymorphicshade if you have time
I would love this enhancement, would it possible?
Than you!

**Comment by Atemu** [comment]
Best way to incentivise other people to work on your feature request is to put up a bug bounty.

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/151621100-c7c35943-1b52-44a4-866f-51cf635efe2d.png)

But like mentioned in the pr, I've probably committed a war crime or two in the threading logic or where the processing gets done. Also is missing a toggle in the settings to disable this feature.

**Comment by Atemu** [comment]
Neat! I'll take a look later.

**Comment by polymorphicshade** [comment]
@tr7zw Good to know upstream decided against this change. Your commits look ok. I'll be sure to include a complete solution in the next release.

**Comment by polymorphicshade** [comment]
If anyone wants to try this out with the code-adjustments I made, here is a debug build:
[newpipe_x_sponsorblock_debug_build.zip](https://github.com/polymorphicshade/NewPipe/files/7965240/newpipe_x_sponsorblock_debug_build.zip)
