### ISSUE TITLE
Add color options

### ISSUE THREAD

**Issue by rahaaatul** [polymorphicshade/NewPipe#126]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] This feature is related to sponsor or ad blocking and/or has explicitly been rejected upstream. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Add theme schemes such as Dracula, Nord, Cherry Pink etc with Light and Dark options. Also add a custom color picker to change both surface color and background color.

#### Why do you want this feature?

Current theme is dull looking, only red and white/dark/black.

**Comment by Atemu** [comment]
Request this feature upstream.

**Comment by Atemu** [comment]
https://github.com/TeamNewPipe/NewPipe/issues

**Comment by polymorphicshade** [comment]
Closing because this feature should first be requested upstream.
