### ISSUE TITLE
SponsorBlock causing UI lag

### ISSUE THREAD

**Issue by kakolisgay** [polymorphicshade/NewPipe#13]
### Checklist

- [x] I am using the latest version - 0.20.5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

The SponsorBlock implementation seems to be running on the UI thread, which causes slowdown and can cause the video to fail loading if the user jumps to the home screen or another app. Ideally this should be done in the background.

**Comment by polymorphicshade** [comment]
This should now be fixed in release [v0.20.6](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.20.6) (see commit cbcb0f7).
