### ISSUE TITLE
Add Timestamps

### ISSUE THREAD

**Issue by Barmarel** [polymorphicshade/NewPipe#134]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This feature is related to sponsor or ad blocking and/or has explicitly been rejected upstream. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
Please add this technology: https://github.com/ris58h/youtube-timestamps if possible.

#### Why do you want this feature?
This is a good improvement.

**Comment by Atemu** [comment]
How is this supposed to work on a touch screen?

**Comment by Barmarel** [comment]
> How is this supposed to work on a touch screen?

I think a list, such as that displayed when the author specifies the time codes in the description.

**Comment by polymorphicshade** [comment]
I have no plans on implementing this, but if someone else wants to I'll be happy to merge in the change.
