### ISSUE TITLE
Add support for submitting dislikes\likes to returnyoutubedislike API

### ISSUE THREAD

**Issue by Anarios** [polymorphicshade/NewPipe#135]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This feature is related to sponsor or ad blocking and/or has explicitly been rejected upstream. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Currently NewPipe only shows number of dislikes retrieved from returnyoutubedislikeapi.com. Would be cool if it was possible to submit scores as well.

#### Why do you want this feature?

It will improve quality of dislike estimates for everyone.

**Comment by Anarios** [comment]
On the other hand, user's don't login into their YouTube accounts with NewPipe? Then, I guess, this shouldn't be implemented (as we want to keep dislike counts close to "real" dislikes that video author sees in YouTube studio)

**Comment by polymorphicshade** [comment]
Closing as I have no plans to implement something like this.

**Comment by Anarios** [comment]
> Closing as I have no plans to implement something like this.

At least making it an option would be nice. Otherwise there's a big chunk of users who see dislikes but do not contribute to the dislike counts. Making experience worse for everyone.

**Comment by BrightDV** [comment]
> At least making it an option would be nice.

I agree with you, but if the users can only dislike videos, it is a bit strange...

**Comment by Anarios** [comment]
> > At least making it an option would be nice.
> 
> I agree with you, but if the users can only dislike videos, it is a bit strange...

Both likes and dislikes should be submitted.

**Comment by polymorphicshade** [comment]
To make things more clear - I will never implement functionality that allows a user to "submit" something to an API, as this goes against the entire point of NewPipe. If you want to be able to submit likes, dislikes, sponsor segments, comments, or stuff like that, then NewPipe isn't the app for you.

**Comment by Anarios** [comment]
> To make things more clear - I will never implement functionality that allows a user to "submit" something to an API, as this goes against the entire point of NewPipe. If you want to be able to submit likes, dislikes, sponsor segments, comments, or stuff like that, then NewPipe isn't the app for you.

Well, it already leaks view history.

**Comment by Atemu** [comment]
That's true. Please implement K-anonymity to remedy that fact.
