### ISSUE TITLE
{dis,}like segments

### ISSUE THREAD

**Issue by binex-dsk** [polymorphicshade/NewPipe#140]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

allow the user to like or dislike sponsor segments

### Why do you want this feature?

To provide feedback to the database

### Additional information

<img alt="PXL_20220220_224324576" src="https://user-images.githubusercontent.com/65276418/154887584-98623bdd-128e-41ad-8734-a23b6e974c9a.jpg" height=600 />

My Cat

**Comment by polymorphicshade** [comment]
I will not be doing this (see https://github.com/polymorphicshade/NewPipe/issues/15).
