### ISSUE TITLE
denied so many times by newpipeTeam for no reason: sleep timer 

### ISSUE THREAD

**Issue by MD77MD** [polymorphicshade/NewPipe#142]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

To be able to set a timer to stop playback with presets
[15, 30, 60, custom]
or something like that

action:
• stop playback 
• close NewPipe ( although not important but for the sake of completeness )

### Why do you want this feature?

for two reasons:

to be able to use before bed, so i can fall asleep while listening to music or audiobook or even relaxing sounds without worrying to be woken up by some sharp sound from one of the videos in the playlist.

not wast internet bandwidth nor phone battery

### Additional information

this feature has been requested so many times by users... and each time it has been denied for no reason just because. .. you can check yourself, just search for "sleep timer".

It is very simple yet very useful in so many ways... i really wish for you to consider it 😅  as you are the last hope for many users 🤩

**Comment by Atemu** [comment]
Looks like the feature request was closed due to a misunderstanding. It hasn't been denied multiple times either, they just closed the useless duplicate feature requests.

@TobiGr actually said they want to ship the feature in the first comment of [the PR](https://github.com/TeamNewPipe/NewPipe/pull/2892) which had massive technical issues. (It also implemented MP3 conversion, wtf?).  
It was closed because of these and because it was abandoned, not because the feature isn't wanted.

Take this upstream.

**Comment by MD77MD** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/2830#issuecomment-932482364

> Although this was closed it popped up again in #2892
> 
> My opinion to this topic: Out of scope - this is primary an app for playing videos and music. If you need a timer use a timer app 😄
> 
> Also newer Android versions (probably 9+, vendor specific) are shipped with a automatic shutdown/start functionality (`Schedule power off/on`) which powers off the complete phone and not just NewPipe 😉

https://github.com/TeamNewPipe/NewPipe/issues/2830#issuecomment-932482364

this was used to close all requests.... this means no sense... most media players have such feature.. from the countless requests by users,  one should change his assumption and release the relevant of such feature and how it expected in media players

**Comment by Atemu** [comment]
That's just one opinion of one person who seems like they misunderstood what the feature is useful for. Closing the other issues means nothing, it's merely to unify the discussion; they would've done that whether they agree or not.

**Comment by polymorphicshade** [comment]
I have no plans on doing this, but if someone else wants to I'll be happy to merge in the changes.

**Comment by Atemu** [comment]
The upstream issue has been re-opened.

**Comment by MD77MD** [comment]
> The upstream issue has been re-opened.

closing in favor of reopening issue
