### ISSUE TITLE
Newpipe has fixed when switching to pop up video start from initial

### ISSUE THREAD

**Issue by Isssuemaker** [polymorphicshade/NewPipe#147]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.0r_2

### Steps to reproduce the bug

Switch to player and video start from 0:00

### Expected behavior

Video should start from where it is switched

### Actual behavior

The issue has been fixed in latest upstream update but not in sponserblock latest update

**Comment by Atemu** [comment]
You'll have to be more precise in what exactly your issue is and how to reproduce it.

**Comment by Isssuemaker** [comment]
From New Pipe Changelog
Fixed
As the first entry in our big series of fixes this release, a nasty bug a lot of our users faced was that switching from one player type to another caused the playback to restart from the beginning. This has been fixed by @litetex.

**Comment by Isssuemaker** [comment]
> You'll have to be more precise in what exactly your issue is and how to reproduce it.
> 
> I'm having a hard time understanding what you mean.

.

**Comment by BrightDV** [comment]
> Switch to player and video start from 0:00

I have tried with both NewPipe SponsorBlock 0.22.0r_2 and NewPipe 0.22.0, and they worked in the same way.

**Comment by Isssuemaker** [comment]
> > Switch to player and video start from 0:00
> 
> I have tried with both NewPipe SponsorBlock 0.22.0r_2 and NewPipe 0.22.0, and they worked in the same way.

But latest Newpipe is working good but sponser block not

**Comment by brnwlshubh** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/7916#issuecomment-1047171200
Check this

**Comment by Atemu** [comment]
> But latest Newpipe is working

Have you tested this?

**Comment by Isssuemaker** [comment]
> [TeamNewPipe#7916 (comment)](https://github.com/TeamNewPipe/NewPipe/issues/7916#issuecomment-1047171200) Check this

This fixed has worked
