### ISSUE TITLE
Autoskip functionality is broken, seems to skip all silent parts of a video

### ISSUE THREAD

**Issue by newissuemaker** [polymorphicshade/NewPipe#149]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1 

### Steps to reproduce the bug

1. Launch a video, [this](https://www.youtube.com/watch?v=LoCaeI5RffI) and any of the LTT's WAN Show episodes are good choices. 

### Expected behavior

Video should play as intended. 

### Actual behavior

App automatically skips parts of the video that don't feature anything sponsorblock is supposed to skip (intro, sponsor, self promotion etc.). It seems like it skips the silent parts of the video, making the viewing experience choppy and unpleasant. I digged through the settings, this does not appear to be an intended functionality. I tried disabling exoplayer to see if it would make a difference but it didn't. 

### Screenshots/Screen recordings

[Here is a demonstration](https://github.com/polymorphicshade/NewPipe/files/8148464/MP4_20220227_130137.zip)

### Affected Android/Custom ROM version

EMUI 8.1

### Affected device model

Huawei Y7 2019

**Comment by polymorphicshade** [comment]
I can't reproduce this issue. Are you sure the "Fast-forward during silence" feature is disabled?

**Comment by newissuemaker** [comment]
I had no idea this was a thing, I must've accidentally activated by hitting the video speed setting in the player. My apologies, I wasted your time.
