### ISSUE TITLE
Create SponsorBlock segments for videos

### ISSUE THREAD

**Issue by bugreportanon** [polymorphicshade/NewPipe#15]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

On the desktop you are able to create the segments for Sponsor Block contributing to the database helping others using the API out, would be great to have the same tools on mobile so you can contribute when you're not at your desktop.

#### Is your feature request related to a problem? Please describe it

No, it's unrelated to any current issues with implementations of Sponsor Block.

#### Additional context

Refer to the desktop extension for the process of adding new segments for the API to skip.

#### How will you/everyone benefit from this feature?

Would be convenient to be able to add to the database while on mobile instead of having to wait to get to the desktop to add what needs to be skipped.

**Comment by najodleglejszy** [comment]
back when it was a pull request on the main Newpipe Github, there was a discussion about how mobile submissions would be less precise (and thus lower quality) than desktop ones.

**Comment by polymorphicshade** [comment]
I'm going to close this because I have no plans on implementing something like this.

The general point of NewPipe is privacy and in order to let users submit segments, they would have to associate a username. If we want to preserve the privacy-friendly approach of NewPipe, then we could use anonymous usernames - however this would probably result in a clutter of anonymous and potentially inaccurate submissions.

If you really want to submit video segments on mobile, use YouTube Vanced.

**Comment by SameenAhnaf** [comment]
@polymorphicshade Would you please have a talk with ajayy regarding this topic? He may update privacy policy in a better way.

It's really sad that we are enjoying a feature half baked. If we can believe Newpipe, why can't we do the same for Sponsorblock? Lacking this feature will surely let Newpipe lag behind its competitor apps.

**Comment by highbaser** [comment]
> The general point of NewPipe is privacy and in order to let users submit segments, they would have to associate a username. If we want to preserve the privacy-friendly approach of NewPipe, then we could use anonymous usernames

This is exactly what happens in other environments. The SponsorBlock extension generates a **randomized username** on install which you can modify to your own but **only** **if you want**. NewPipe w/ SponsorBlock could do the exact same thing. This is not a privacy issue at all.

> however this would probably result in a clutter of anonymous and potentially inaccurate submissions.

Very unlikely. SponsorBlock has an active community with a voting system where other sponsor blocking users can give feedback on whether segments are valid or not. If they're inaccurate they'll be fixed or deleted. This kind of voting could also be included in your NewPipe fork. Would be very useful.

> If you really want to submit video segments on mobile, use YouTube Vanced.

Why would anyone prefer to use Vanced? It's closed-source, more resource-hungry and less featureful than NewPipe. It doesn't even support video downloading.

Please re-consider including a feature for making SponsorBlock segments with your NewPipe fork.

**Comment by Atemu** [comment]
Please read through the original PR; this topic has already been discussed and it's been decided that sponsor segment submission is not going to happen.

**Comment by highbaser** [comment]
> sponsor segment submission is not going to happen.

Shame. Whatever your reasons are. It's just a shame.

You're doing the same that NewPipe devs did when first SponsorBlock PR was created. [[1]](https://github.com/TeamNewPipe/NewPipe/pull/3205)

So then time to create a third fork or what? Ridiculous. I wouldn't be surprised if this was the result of Google intentionally subverting the community of alternative Youtube clients from behind. Glad they didn't succeed at eliminating youtube-dl though.

**Comment by polymorphicshade** [comment]
@highbaser you got me. Yes I work at Google and this fork is our plan to convert NewPipe into a data-gathering machine to figure out how users submit SponsorBlock segments so we can train our YouTube servers to inject sponsorships directly to the video stream to make blocking sponsors harder to do.

Kidding aside, my original intention was to prevent a bunch of anonymous users throwing NewPipe on their devices and using their anonymity to spam the SponsorBlock servers with bogus segments. My worry was when SponsorBlock gets really popular, other agencies might attempt to use a light-weight client like NewPipe to fight against those who actually contribute to SponsorBlock.

But if someone makes a pull request with the ability to submit segments through NewPipe, and enough people vote for the feature, I would not be opposed to merging it in.

Just for me personally I didn't want to spend time building a segment-submission UI/UX I thought might be easily abused.

**Comment by highbaser** [comment]
So you think it's easier for spammers to install an unofficial 3rd-party APK (NewPipe) on thousands of smartphones, and then start spamming SponsorBlock servers **manually**.

Instead of writing a cURL script to submit random segments with lots of valid video IDs to the SponsorBlock API.

Are you serious? You must be really working for Google. ;) They use the same rhetoric about dumbing down their products and removing (or not adding) useful features. If you don't have a very good reason for your unpopular decision, refer to security™, safety™ and anti-spam™...

**Comment by ajayyy** [comment]
@highbaser Mistakes can be unintentional too, not just malicious. In those cases, removing all segments from one user is very helpful.

I would not like any clients to enable anonymous submissions for that reason.

**Comment by DraconicNEO** [comment]
> @highbaser Mistakes can be unintentional too, not just malicious. In those cases, removing all segments from one user is very helpful.
> 
> I would not like any clients to enable anonymous submissions for that reason. Yes, it is possible to change the userID constantly in the browser extension, but only a malicious user would do it.

Umm all clients technically allow anonymous submissions. The user ID is randomly generated and can be changed constantly, there are also no login requirements.

If there was a problem with Anonymous Submissions SponsorBlock would either have made an account system requiring signing up to them or they would've required you to be signed in to your YouTube account to submit and vote on segments.
