### ISSUE TITLE
App/UI crash clicking video

### ISSUE THREAD

**Issue by Troubadix** [polymorphicshade/NewPipe#154]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

Search video
Click video
Crash

### Expected behavior

Video loads

### Actual behavior

App crash

### Logs

{"user_action":"ui error","request":"ACRA report","content_language":"de-DE","content_country":"DE","app_language":"de_DE","service":"none","package":"org.polymorphicshade.newpipe","version":"0.22.1","os":"Linux Android 12 - 32","time":"2022-03-14 07:12","exceptions":["java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$handleResult$15(VideoDetailFragment.java:1588)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$sNiTcE1PlOABkF-7tJ5ry4WF5GE(Unknown Source:0)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda22.run(Unknown Source:4)\n\tat java.lang.Thread.run(Thread.java:920)\n"],"user_comment":""}

### Affected Android/Custom ROM version

12

### Affected device model

Google Pixel 6 Pro

**Comment by Atemu** [comment]
Does this happen unconditionally?

Does this happen with default settings (export your data and clear the app's storage).

**Comment by polymorphicshade** [comment]
Please verify you cannot reproduce this issue with upstream NewPipe.
