### ISSUE TITLE
Update README to mention RYD integration

### ISSUE THREAD

**Issue by wavetro** [polymorphicshade/NewPipe#157]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

This is a really small request to mention, but I think the README/homepage of this repo should mention or feature the integration it has with returnyoutubedislike.com.

### Why do you want this feature?

After Vanced went under, there's a lot of demand for an alternate YT client that lets you see the dislike database maintained by Anarios and the RYD team. I didn't know this client had this integration until I was pointed to this repo by someone else.

### Why ist the feature relevant to this fork?

Directly mentioning the RYD integration on the README would substantially drive up the user count of this NewPipe fork.

**Comment by Atemu** [comment]
It'd probably have been less effort to fork the repo and do it yourself ;)

Small things like these can be done using only the GitHub UI.

**Comment by wavetro** [comment]
Fair point! I'll attempt a small fork and pull request then (I don't have a strong developer background so you'll have to correct me if that's not how I'm supposed to submit an edit to this repo)

**Comment by Atemu** [comment]
Yeah, just fork and edit the README.md. It's just plain text, so no developer background needed here :)

Once you're done, give your commit a short descriptive title like `README: mention RYD integration`, create the commit and then GitHub will likely already nudge you to create a pull request.

You can also do a cool trick and put `Closes https://github.com/polymorphicshade/NewPipe/issues/157` in the commit message body, that way this issue will automatically be closed when @polymorphicshade merges your PR.
