### ISSUE TITLE
Show video size in resolution changer.

### ISSUE THREAD

**Issue by f1vefour** [polymorphicshade/NewPipe#161]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I would like to see the size of the video in the resolution selection menu, this feature is already part of the downloader.

### Why do you want this feature?

Because bandwidth is limited for many people.

### Why ist the feature relevant to this fork?

To make the fork better.

**Comment by Atemu** [comment]
Ask upstream, this has nothing to do with our fork.

**Comment by f1vefour** [comment]
Sure, thanks anyway.
