### ISSUE TITLE
Paint it black

### ISSUE THREAD

**Issue by rahaaatul** [polymorphicshade/NewPipe#165]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

For the love of (whatever you love), make this thing Black/Gray for Black Theme (Whatever feels aesthetically looks good to you).
See [this](https://github.com/polymorphicshade/NewPipe/issues/165#issuecomment-1077491890).

![Screenshot_2022_0323_233416](https://user-images.githubusercontent.com/86149861/159761259-9d26bf2c-6d6f-4ac9-967d-083bc037faf9.jpg)

### Why do you want this feature?

This red bar is annoying AF, and teamnewpipe doesn't wanna do it either.

### Why is the feature relevant to this fork?

It's not, but It's necessary. And you're the last hope who might do it!

### Special Request

If you can't do it with the main, can you at least make another variant with the repainted version, please?

**Comment by rahaaatul** [comment]
I have opened this issue
#124 upstream, and [they rejected it](https://github.com/TeamNewPipe/NewPipe/issues/8095).

**Comment by rahaaatul** [comment]
I have opened [this issue](https://github.com/polymorphicshade/NewPipe/issues/126) upstream, and [they rejected it](https://github.com/TeamNewPipe/NewPipe/issues/8095).

**Comment by mhmdanas** [comment]
> teamnewpipe don't wanna do it either.

Who said that we didn't? The issue you opened was for theme customization, which is a different thing.

**Comment by rahaaatul** [comment]
> > teamnewpipe don't wanna do it either.
> 
> Who said that we didn't? The issue you opened was for theme customization, which is a different thing.

That was my initial issue here too. And @polymorphicshade said to create the issue upstream and I did and it was rejected. So I created a new issue here just to recolor it, would you guys do it? I don't think so.

**Comment by Atemu** [comment]
@mhmdanas this pretty much implies theming support. Changing the theme is a highly subjective thing and not all users would like it.

@rahaaatul please see a doctor ASAP.

**Comment by mhmdanas** [comment]
> @mhmdanas this pretty much implies theming support. Changing the theme is a highly subjective thing and not all users would like it.

What I had in mind wasn't changing the current theme, but perhaps adding a pitch black one.

**Comment by mhmdanas** [comment]
> And @Atemu said to create the issue upstream and I did and it was rejected.

Your issue (https://github.com/TeamNewPipe/NewPipe/issues/8095) did NOT ask for a pitch black theme; it asked for the ability to customize the colors in-app. That's why it was rejected.

**Comment by rahaaatul** [comment]
@mhmdanas 
> What I had in mind wasn't changing the current theme, but perhaps adding a pitch black one.
 [https://github.com/TeamNewPipe/NewPipe/issues/4148](#4148)

> Your issue (TeamNewPipe#8095) did NOT ask for a pitch black theme; it asked for the ability to customize the colors in-app. That's why it was rejected.

And I didn't deny that. And this issue is about recoloring the existing theme, not adding one. Also, I exactly, DID NOT ask for a PITCH BLACK THEME here either. I do not want argue about this anymore, please. You could have already opened a issue there about adding a new theme, instead you came here for what I don't know, just to prove yourself right? you win. 

I don't care if Poly accepts my idea or not, perhaps he will add this as a new theme. His call. Please, open a new issue if you want, I'm not creating any issue there. I'm done with this.

**Comment by rahaaatul** [comment]
Thank you for your concern. @Atemu

I'll see if it happens again, tonight. Also, I was regularly dealing with hypnotic jerks, when you feel like you're falling in your sleep. I hope they're not connected somehow.

**Comment by mhmdanas** [comment]
I opened https://github.com/TeamNewPipe/NewPipe/issues/8110.

**Comment by rahaaatul** [comment]
> I opened https://github.com/TeamNewPipe/NewPipe/issues/8110.

Thanks, if they do consider it let them about this color scheme #167.

**Comment by mhmdanas** [comment]
I edited my issue to mention #167.

**Comment by Atemu** [comment]
> perhaps adding a pitch black one

Adding a theme requires theming support; there need to be multiple ones and user needs to be able to choose.

**Comment by mhmdanas** [comment]
@Atemu I misunderstood your suggestion to be allowing complete customization of the app colors. Anyway, doesn't NewPipe already have multiple themes? There are three themes: black, dark, and light.

**Comment by Atemu** [comment]
Oh. It does!

Sorry for the noise then.

In that case you should be able to submit your changes in the form of a new theme to upstream NewPipe @rahaaatul.

**Comment by rahaaatul** [comment]
> Oh. It does!
> 
> Sorry for the noise then.
> 
> In that case you should be able to submit your changes in the form of a new theme to upstream NewPipe @rahaaatul.

How do I do that? I have edited colors of the dark theme.

**Comment by Atemu** [comment]
Not exactly sure either but I think you'd create a new theme file just like the black theme and declare it somewhere. Check how the old theme was added, it should give you hints on how to do that.

**Comment by rahaaatul** [comment]
> Not exactly sure either but I think you'd create a new theme file just like the black theme and declare it somewhere. Check how the old theme was added, it should give you hints on how to do that.

The last time this guy repainted the colors in NewPipe#6244

**Comment by polymorphicshade** [comment]
Closing this as I won't be messing with any theming until I do the "Tubular" rebranding. Any color customization should be done in upstream NewPipe.
