### ISSUE TITLE
Login to Piped Account

### ISSUE THREAD

**Issue by ghost** [polymorphicshade/NewPipe#166]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

A cool feature would be to be able to login to one or multiple Piped accounts and be able to subscribe/unsubscribe to and from channels, access your feed, and create playlists (once piped supports playlists) within the NewPipe app.

Piped has a good privacy policy unlike a google account, you can register on Piped without a email!

Please allow us to choose the Piped instance as well. Not everyone uses piped.kavin.rocks as their instance.

Piped is essentially the same thing as Invidious but much smoother, with the video loading most of the time compared to Invidious. Piped also used the Newpipe Extractor to fetch videos!

### Why do you want this feature?

The NewPipe developers doesn't include this feauture yet.

### Why ist the feature relevant to this fork?

This make NewPipe x SponsorBlock more unique!

**Comment by Atemu** [comment]
> The NewPipe developers doesn't include this feauture yet.

Unless they explicitly rejected it, this is not the place to discuss it.

**Comment by RandomIrrelevantUsername** [comment]
I like this idea.

**Comment by polymorphicshade** [comment]
I'm not planning on doing this, but I am planning on implementing YouTube login functionality.

**Comment by trymeouteh** [comment]
Would like to see this. Piped is way to have a subscription feed synced on all devices without Google spying. A google account logs your subscription feed, watch history and more. You can also self host your own Piped instance.
