### ISSUE TITLE
Auto full-screen when turning landscape. 

### ISSUE THREAD

**Issue by Fatcakes** [polymorphicshade/NewPipe#17]
Anyway this can be implemented? I know we don't want to veer to far away from the original project, but I don't see them putting back this feature they removed.

**Comment by polymorphicshade** [comment]
I'll give this a shot, I don't imagine it would be all that hard.

**Comment by polymorphicshade** [comment]
Actually I just tried this out... it seems like NewPipe already does this...
Does this work for anyone else?

**Comment by Fatcakes** [comment]
@polymorphicshade I have your lastest build and it doesn't for me. You to turn it sideways the hit the maximize square. Maybe it's because of a dpi setting and it recognizes my phones as tablet? This has been and issue for me since the update to version 20.

Thanks again @polymorphicshade for your work and this fork. Just know that you're appreciated. 👍

**Comment by polymorphicshade** [comment]
@Fatcakes interesting... what model/android version is your phone? On my physical device, and 3 emulators I've tried, all of them auto full-screen when rotating the phone.

I'll poke around the code more and see what I can find. In the mean time, I hope others can chime in and see how their phone reacts.

**Comment by Fatcakes** [comment]
@polymorphicshade I'm using a Nexus 6 running lineageos 15.1 oreo 8.1.0 (old I know lol)

**Comment by Fatcakes** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/Qu5PXbQ" data-context="false" ><a href="//imgur.com/a/Qu5PXbQ"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by polymorphicshade** [comment]
@Fatcakes oh yeah I see now... it looks like your phone is seen as a tablet. That layout you see is NewPipe using the "large-land" varient of the player UI, so it looks like NewPipe is behaving normally.

I'm not very familiar with Lineage OS but I wonder if you change your DPI somewhere in dev settings you may get different results.

**Comment by Fatcakes** [comment]
@polymorphicshade I changed the display size back to default and that fixed it. However that makes everything on my screen huge and I cant use my phone that way. Is there anyway that we can put a selector in there that forces the phone ui?

**Comment by polymorphicshade** [comment]
@Fatcakes good idea! I can throw in some kind of "disable tablet layout" setting somewhere.
I'm thinking of reorganizing the SponsorBlock settings into it's own section, perhaps we could have an "Extras" section for miscellaneous tweaks like that tablet setting.

**Comment by Fatcakes** [comment]
@polymorphicshade that sounds great my dude. Again, thank you for hard work. 👍

**Comment by polymorphicshade** [comment]
@Fatcakes give [this debug APK](https://github.com/polymorphicshade/NewPipe/files/5693927/newpipe_x_sponsorblock-debug.zip) a try and let me know how it works for you.

**Comment by Fatcakes** [comment]
@polymorphicshade you're a damn machine! It works. Haven't noticed any bugs yet. It still takes 2-3 seconds to transition which has persisted since the 20 update, and I'm sure part of that is they old hardware in using. I approve of the cleansed up settings menu as well. 👍

**Comment by polymorphicshade** [comment]
@Fatcakes pog. This should be in the next "official" release then (if not slightly tweaked).
I'm gonna close this issue since this isn't really an issue with the auto full-screen functionality.
