### ISSUE TITLE
show above other apps

### ISSUE THREAD

**Issue by TeaqariaWTF** [polymorphicshade/NewPipe#181]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

touchscreen no longer works when i try to run app in background

### Expected behavior

device should respond to touches when app is backgrounded

### Affected Android/Custom ROM version

Android 12.1 / ArrowOS

### Affected device model

Poco X3 NFC

**Comment by TeaqariaWTF** [comment]
Video link : https://gofile.io/d/NOuWC0

**Comment by polymorphicshade** [comment]
I find it hard to believe this issue would exist only on this fork and not the upstream NewPipe.
Did you actually verify that this behavior doesn't exist on the upsteam version of NewPipe?

**Comment by TeaqariaWTF** [comment]
https://gofile.io/d/nPEcqD

I took a video like this because screen recording doesn't record touches

**Comment by polymorphicshade** [comment]
Unless I missed something, but that video doesn't show the bug on the upsteam (vanilla) NewPipe. Nonetheless I know NewPipe has known issues related to PIP (picture-in-picture) mode so I'm going to close this issue unless you can prove upstream NewPipe _**does not**_ have this issue.

**Comment by TeaqariaWTF** [comment]
I did not understand what you said 
 touchscreen not working when newpipe gets in front of other apps
