### ISSUE TITLE
Pip mode

### ISSUE THREAD

**Issue by TeaqariaWTF** [polymorphicshade/NewPipe#185]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

I open any video in PIP mode and the touchscreen is not working

### Affected Android/Custom ROM version

 ArrowOS Android 12.1

### Affected device model

Poco X3 NFC

### Additional information

MatLog : https://gofile.io/d/Ys2aEZ

**Comment by polymorphicshade** [comment]
I believe that this is fixed in the [latest release](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.23.0). In the future, please make sure an issue doesn't exist on the vanilla NewPipe version before submitting a bug report.

**Comment by TeaqariaWTF** [comment]
Problem solved with new update
