### ISSUE TITLE
Fullscreen Scaling doesnt work properly on non-16:9 phone

### ISSUE THREAD

**Issue by qube-03** [polymorphicshade/NewPipe#186]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

1. Play a video
2. Fullscreen it by pressing the button (sometimes the video is too small but thats a newpipe upstream issue
3. the video zooms in to the edges of the screen and doesnt respect the 16:9 nature of the video

### Expected behavior

have the video scale correctly, with black borders on the sides to compensate for the aspect ratio

### Actual behavior

video zooms in to the edges of the whole display, cutting off lower and upper parts

### Screenshots/Screen recordings

![Screenshot_20220425-220152_NewPipe SponsorBlock](https://user-images.githubusercontent.com/92535344/165165724-60774aa7-39de-49c5-b0ad-e35b95a98bd0.png)
![Screenshot_20220425-220159_NewPipe SponsorBlock](https://user-images.githubusercontent.com/92535344/165165741-0942f373-155e-4627-95c1-0ee9daf6dfc8.png)

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy S20 FE

### Additional information

i removed a lot of google stuff like gms with adb but i doubt thats the issue

**Comment by Atemu** [comment]
How does upstream NewPipe behave here?

**Comment by qube-03** [comment]
instead of stretching across the screen like in screenshot 1, the videos are in a quarter of the screen i guess. when going to your recently opened apps (you know where you see what apps are open) and going back to newpipe to reload the video and fix the issue the video scales fine.
this presumably is random
![Screenshot_20220426-140309_NewPipe](https://user-images.githubusercontent.com/92535344/165295839-bf6abd29-1225-443e-b8fc-b13c9cecc233.png)

**Comment by qube-03** [comment]
ok so i reinstalled and with default settings and having it set up again it behaves like upstream so this is some setting issue. closing.
