### ISSUE TITLE
Can a build based on 0.23 beta be built?

### ISSUE THREAD

**Issue by 0mni** [polymorphicshade/NewPipe#187]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Can a build based on 0.23 beta be released? There is a pretty bad bug with A12 and popup videos that is breaking of the app. It is apparently fixed in 0.23 beta +

### Additional information

https://github.com/TeamNewPipe/NewPipe/issues/6770

**Comment by polymorphicshade** [comment]
See [here](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.23.0) for the latest release. Note that in the future, I will not be making beta builds.

**Comment by 0mni** [comment]
> See [here](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.23.0) for the latest release. Note that in the future, I will not be making beta builds.

I appreciate doing that, it works perfectly!
