### ISSUE TITLE
Equalizer support 

### ISSUE THREAD

**Issue by SHREYASHMJ** [polymorphicshade/NewPipe#192]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Add option to Third party Equalizer in Settings 

### Why do you want this feature?

Because of YT also giving the same features with Equalizer support 

### Why ist the feature relevant to this fork?

Please Add This Feacher in settings

**Comment by Atemu** [comment]
Open an issue upstream, this has nothing to do with this fork.
