### ISSUE TITLE
Automatic video quality

### ISSUE THREAD

**Issue by Nizami20052022** [polymorphicshade/NewPipe#193]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

With this, people will watch online video in automatically tuned quality according to internet speed! 

### Why do you want this feature?

This will make it easier and faster for people to watch videos 

### Why ist the feature relevant to this fork?

It is not difficult to add this feature

**Comment by Atemu** [comment]
In other words it isn't relevant to this fork at all. Request this feature upstream.
