### ISSUE TITLE
Extend Caching beyond the next segments

### ISSUE THREAD

**Issue by yoshimo** [polymorphicshade/NewPipe#196]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I often notice stuttering when skipping large segments , especially at the beginning of the video.
It seems that the pre-loading doesn't extend beyond the segments that are about to be skipped.
I Therefore think we should pre load past the next segments, no matter their duration.

### Why do you want this feature?

A smoother transition and less stutter.

### Why ist the feature relevant to this fork?

Because the segments that are skipped by this fork seem to introduce the lag and the original client feels smooth.

**Comment by Atemu** [comment]
Problem is that an increase in cache size implies an increase in memory usage which isn't always an option with low-end phones.

Ideally, we would skip caching sponsored segments but I'm not sure exoplayer allows that.

**Comment by polymorphicshade** [comment]
I noticed that the stuttering mostly goes away with the new streaming method upstream NewPipe implemented. The skipping is nothing more than a manual seek, so I don't think this kind of problem is specific to my fork.
