### ISSUE TITLE
App crashes on open

### ISSUE THREAD

**Issue by Gravity2106** [polymorphicshade/NewPipe#197]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

App crashes when I try to open. I was watching a video, it worked fine (with buffering issues). This happened to me before and I had to delete the app and install it again. Update it doesn't fix it. I have tried deleting cache

### Expected behavior

App doesn't crash

### Actual behavior

App crashes when I open it

### Affected Android/Custom ROM version

MIUI 12.5.2

### Affected device model

Xiaomi Mi 8

**Comment by polymorphicshade** [comment]
Try using the latest version. If you still have this issue, please post the crash log and I'll re-open this issue.
