### ISSUE TITLE
App crashes when fullscreen and autoplay is enabled

### ISSUE THREAD

**Issue by MrBKA95** [polymorphicshade/NewPipe#198]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Go to settings
2. Select Video and Audio
3. Enable 'Start mainplayer in fullscreen'
4. Select 'Autoplay' to always
5. Go back to main page and select any video

### Expected behavior

The video should automatically play and the screen should automatically go into landscape mode with no issues.

### Actual behavior

In the video and audio settings when I have 'Start mainplayer in fullscreen' and 'Autoplay' settings enabled the video freezes and the app crashes. I downloaded the standard NewPipe app and these features worked fine so this bug is only related to 0.23.0 version of NewPipe Sponsorblock.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$handleResult$15(VideoDetailFragment.java:1588)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$sNiTcE1PlOABkF-7tJ5ry4WF5GE(Unknown Source:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda22.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:920)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy S21

**Comment by polymorphicshade** [comment]
I can't reproduce this issue. Try this on the latest version of my fork, and the latest version of upstream NewPipe.
If you still run in to this problem I'll re-open this issue.
