### ISSUE TITLE
Optional YT login

### ISSUE THREAD

**Issue by KAMiKAZOW** [polymorphicshade/NewPipe#20]
Another feature upstream NewPipe refuses to implement is completely optional YouTube login.

For people who only use YouTube via NewPipe on their phone, offline-only subscription management and playlists might be fine but those who'd like to use it in conjunction with the desktop website would benefit from this.

This feature should be completely optional. Heck, there might even be a privacy warning displayed.

**Comment by polymorphicshade** [comment]
Closing this because implementing a login kind of feature goes completely against the point of NewPipe.

**Comment by KAMiKAZOW** [comment]
This isn't NewPipe, though. 🤦‍♂️ The "arguments" by NewPipe are completely braindead anyway. An optional feature does not increase reliance on Google, duh.

Fine then, this makes this app completely irrelevant for all people whose phone don't have Google Services, yet want to use regular YouTube. \*unsubscribing\*

**Comment by test2a** [comment]
You should use YouTube vanced to get login credentials

**Comment by Red-Baran** [comment]
Anyway your mind has changed on this? You're the only really close alternative. It's nice for idiots like me who pay for YT Premium and live on YT (like 60 hours a week) so I have a decent queue. 
Either way I greatly appreciate what you are trying to do!!! Thank you.

**Comment by polymorphicshade** [comment]
@Red-Baran see here: https://www.reddit.com/r/NewPipe/comments/tg2spq/an_update_about_my_fork/
