### ISSUE TITLE
Download videos with sponsorblock

### ISSUE THREAD

**Issue by sybenx** [polymorphicshade/NewPipe#200]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Download videos with sponsorblock sections optionally chapter marked or removed as is featured in yt-dlp

### Why do you want this feature?

So I don't have to use a separate program to download videos

### Why ist the feature relevant to this fork?

This fork uses SponsorBlock

### Additional information

This is the relevant section describing this functionality in yt dlp:
https://github.com/yt-dlp/yt-dlp#sponsorblock-options

**Comment by polymorphicshade** [comment]
So you can actually do this right now. You can enable the experimental built-in player (setting is found in the Extras menu). Any downloaded videos played with the built-in player will have skippable SponsorBlock segments, though you won't see any visual indicators.
