### ISSUE TITLE
Seekbar thumbnail preview

### ISSUE THREAD

**Issue by cyanwolfg** [polymorphicshade/NewPipe#201]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Open some video with Seekbar thumbnail preview option enabled
2. Swipe seekbar on forward or backward

### Expected behavior

Show a thumbnail up to seekbar

### Actual behavior

Thumbnail shows on middle player. This is most notorious on tablets or large screens. On phone this happen when video is on fullscreen.

### Screenshots/Screen recordings

![Screenshot_20220608_173752_org polymorphicshade newpipe](https://user-images.githubusercontent.com/101049163/172730568-4e94a196-7678-415c-a156-8b653775d9cc.jpg)
![Screenshot_20220608_173802_org polymorphicshade newpipe](https://user-images.githubusercontent.com/101049163/172730572-f15cd1a3-a431-4556-af04-55e56d3e9dea.jpg)

### Affected Android/Custom ROM version

Android 10

### Affected device model

Huawei MatePad 10.4 / Samsung Galaxy S9 / Xiaomi MI PAD 4

**Comment by Atemu** [comment]
Is this always reproducible from a fresh start? NP's UI can often temporarily glitch out.

If this is reproducible on 0.23.0, I'm *not* seeing this on 0.22.0.

**Comment by cyanwolfg** [comment]
I do a fresh install of 0.22.0 and everything looks good.

Fresh install of 0.23.0 always show bug.

**Comment by lawson85** [comment]
0.23.1 is out so try updating

**Comment by cyanwolfg** [comment]
Fresh install on last 0.23.1 bug still present.
I share a screenshot with original Newpipe and Sponsorblocks version. This is on my smartphone but is present on my tablets too.
![IMG_20220710_141345_715](https://user-images.githubusercontent.com/101049163/178158802-b76102ad-05d4-482b-8ceb-9b64d09ef1dd.jpg)
![IMG_20220710_141345_690](https://user-images.githubusercontent.com/101049163/178158806-af70a486-fb7f-4836-b54b-8c6ee4f2c5a8.jpg)

**Comment by polymorphicshade** [comment]
Fixed in release [0.23.1 R1](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.23.1_r1).
