### ISSUE TITLE
Remote for Android TV

### ISSUE THREAD

**Issue by dawidmachon** [polymorphicshade/NewPipe#204]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

On official YT app or vanced, there is a way to connect to TV. Does this app support that feature or will be in future?

To cast videos from your phone (or other devices), you must link that device to your TV.  How to link your smartphone and TV:

open YT and go to settings
go to settings > General > watch on TV
click on connect using TV-code and enter the code from your TV

**Comment by Atemu** [comment]
AFAIK, you can install NewPipe on your TV. I don't think it's been tested by I would be surprised if this fork didn't also work.

**Comment by dawidmachon** [comment]
Ok, but with standard client?
or where in NewPipe is option to connect by code?

**Comment by hdbg** [comment]
@dawidmachon I think this YT feature provided by Google services thus not possible to implement in NewPipe.

**Comment by polymorphicshade** [comment]
Closing this as this isn't relevant to my fork.
