### ISSUE TITLE
merge pr (Add play queue button to video details fragment)

### ISSUE THREAD

**Issue by MD77MD** [polymorphicshade/NewPipe#205]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

in pr https://github.com/TeamNewPipe/NewPipe/pull/8424#issue-1243357902 about Adding a play queue button to video details fragment (small player bar at the bottom of the screen)

please check it out and if you agree with it merge it with your fork.

### Why do you want this feature?

everyone is wanting it for this reason https://github.com/TeamNewPipe/NewPipe/pull/8424#issuecomment-1144658509

the problem with implementing it in main menue is it would be easily blocked... because the side menu is only accessible from the main page and would be blocked the moment you open anything in newpipe

so you will have to go back to the main page to open queue which not right... queue should be easliy accessed regardless to whats opened in NewPipe

that's why @HybridAU closed the main menue pr and opend this one

please refer to #8419 (comment), #8419 (comment)

### Why ist the feature relevant to this fork?

like SponsorBlock,  stybox refused it for no real reason please see

https://github.com/TeamNewPipe/NewPipe/pull/8424#issuecomment-1166361095

### Additional information

https://github.com/M1CK431 has expressed his readiness to maintain it too please see comments https://github.com/TeamNewPipe/NewPipe/pull/8424#issuecomment-1166361095

**Comment by polymorphicshade** [comment]
I'm closing this because while I think it's a neat addition, it is clearly a quick "hack". If I were to merge several small "hacks" towards a goal, the code and UI can very quickly become unmanageable. I'd much rather wait for a "good" solution upstream before I add something like this to my fork.
