### ISSUE TITLE
Is this fork still being maintained?

### ISSUE THREAD

**Issue by cheater** [polymorphicshade/NewPipe#206]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

I am asking since this fork is 2-3 months behind upstream. No disrespect intended, just want to know what the status is.

**Comment by Atemu** [comment]
What do you mean by that? This fork is up to date with the latest upstream release.

**Comment by cheater** [comment]
OK, I thought NewPipe upstream is being built off dev, but instead it's being built off master. Never mind then!

**Comment by AkiraNoSushi** [comment]
> What do you mean by that? This fork is up to date with the latest upstream release.

Not anymore! 👀

**Comment by Atemu** [comment]
https://github.com/polymorphicshade/NewPipe/pull/207
