### ISSUE TITLE
"View on github" button In the about page doesn't open link to newpipe x sponsorblock's github page

### ISSUE THREAD

**Issue by FuriousGamer1356** [polymorphicshade/NewPipe#208]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Changing the "View on github" button in the about page to open newpipe x sponsorblock's github page.

### Why do you want this feature?

Changing the link would allow quick access to the github page, and thus a lot easier to get to said github page.

### Why ist the feature relevant to this fork?

The "View on github" button in the about page of the official newpipe app opens to it's github page, so why not do the same and the button open newpipe x sponsorblock's github page?

### Additional information

Please bear with me, I am very new to github!

**Comment by Atemu** [comment]
It's a very minor thing but valid I guess.

W.r.t. GitHub, you did everthing right! Welcome.
