### ISSUE TITLE
Option to enable/disable the "fact check" box

### ISSUE THREAD

**Issue by Fatcakes** [polymorphicshade/NewPipe#22]
I see they added it. I wish they hadn't. Can we get the option to disable it?

**Comment by polymorphicshade** [comment]
@Fatcakes Are you talking about the COVID-19 information stuff?

**Comment by Fatcakes** [comment]
@polymorphicshade Covid, the 2020 election, flat earth, conspiracy shit. It's not needed.

**Comment by polymorphicshade** [comment]
@Fatcakes oh I see, yeah this shouldn't be too hard. I can throw in a setting in the Extras category.

**Comment by polymorphicshade** [comment]
@Fatcakes actually I think a setting for that is already in the app. Does disabling the "Show meta info" setting in the Content category do what you want it to do?

**Comment by Fatcakes** [comment]
@polymorphicshade I'm an idiot. Yes, that gets rid of it. Thanks again my dude.
