### ISSUE TITLE
Feature req#

### ISSUE THREAD

**Issue by knightmob** [polymorphicshade/NewPipe#223]
Hello! This app is really good! Almost complete, one thing though can you pls add a reply section, it's ok if I can't reply to the messages but at least make it visible like the reply section in the app pls, overall the app is really sick! Keep up the good work devs! more stars to earn

**Comment by Atemu** [comment]
Use the template.

This is a feature request for upstream NewPipe, it has nothing to do with our fork. Preparations for this have already happened actually.

**Comment by knightmob** [comment]
My bad, aight thanks

**Comment by Invisigon1** [comment]
Oooh, this is so good. Can't wait to finally be able to see replies without needing to open in Firefox.
