### ISSUE TITLE
Show channel playlist with channel info..(like youtube)

### ISSUE THREAD

**Issue by heartlog** [polymorphicshade/NewPipe#224]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Well, i like your work PolyM...💖
# What's feature and why ?
Well, while operating newpipe the major problem I always face is not been able to see __playlist on channels__ info ...

If you don't understand
Then, it's 
<img alt="Screenshot_20220808-193801_NewPipe SponsorBlock" src="https://user-images.githubusercontent.com/76758776/183438500-8b69b003-e800-41f4-b83d-fe9b75e934a3.jpg" height=600 />

### Why do you want this feature?

While operating newpipe i am not able to see the channels playlist listing (like youtube channel info have). Because of that I had to always use yt for coping link. And pesting it to newpipe.....

### Why ist the feature relevant to this fork?

It'll be a lot easier to access the content while avoiding access scrolling on channel to find specific catagory videos on newpipe.

### Additional information

# What's youtube playlist listing?
Here it is 👇
<img alt="Screenshot_20220808-194956" src="https://user-images.githubusercontent.com/76758776/183440100-c606bf1f-92ed-464b-963c-c8b5fdcdda91.jpg" height=600 />

# What I Request to add ?
👇{Something like this}
<img alt="Screenshot_20220808-193801_NewPipe SponsorBlock" src="https://user-images.githubusercontent.com/76758776/183438500-8b69b003-e800-41f4-b83d-fe9b75e934a3.jpg" height=600 />

**Comment by heartlog** [comment]
I edited like a pro on Photoshop for 10 hr for this two shots... LOL

I requested this request to newpipe you can see that here https://github.com/TeamNewPipe/NewPipe/issues/8749
So, @polymorphicshade I came to you for this..
Hope you won't disappoint me 🥰🥰

**Comment by Atemu** [comment]
Stypox already directed you to the [upstream issue](https://github.com/TeamNewPipe/NewPipe/issues/2414) and explained that simply nobody had the motivation to work on it yet.

If Poly, me or anyone else were to implement it, they'd do it upstream.

This fork exists for features that upstream explicitly rejects for non-technical reasons. All the features upstream gets, we get too.  
I'd love to be able to access channel playlists too but this is not the place to request or implement it.

**Comment by polymorphicshade** [comment]
I have no plans on implementing this. Hopefully upstream NewPipe will have this eventually.
