### ISSUE TITLE
Add Support for Rumble

### ISSUE THREAD

**Issue by LeonryLight** [polymorphicshade/NewPipe#225]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Rumble is another video plataform that is also corporate, but has way more lean way when it comes to political discourse and free speech.

### Why do you want this feature?

\Rumble is a very good alternative platform YouTube now that its becoming more and more censorious.

### Why ist the feature relevant to this fork?

Supporting more plataforms is always better so the user can keep only one app. Also the Official app for Rumble is kind of bad and collects way too much metadata.

### Additional information

Rumble and Bitchute support was already added to this fork:
https://github.com/bravenewpipe/NewPipe
So probably wont be much of an effort to use the code from there to add here and unite all features in just one app.

**Comment by Atemu** [comment]
> way more lean way when it comes to political discourse and free speech.

Does that mean it's full of nazis, conspiracy believers and other societal cancer? If so, I doubt anyone is willing to implement that.

And why should this not go upstream?

**Comment by LeonryLight** [comment]
> > way more lean way when it comes to political discourse and free speech.
> 
> Does that mean it's full of nazis, conspiracy believers and other societal cancer? If so, I doubt anyone is willing to implement that.
> 
> And why should this not go upstream?

Ive seen Nazi discourse in Bitchute, but never on Rumble. Rumble is way more corporatized and mainstream, they even have shares in the New York Stock Market. They differ from Youtube because they dont censor medical dissent and questioning of "science", the ex president, libertarians and anti-war left-wing personalities. All I can say is go check yourself. A lot of regular political commentators mirror they content to Rumble because they never know when Youtube will just ban them for no reason (left and right wing content creators, I can cite exemples for you from both side if you want).

I dont know why it shouldnt go upstream. Just feel like the original devs either find freer speech offensive to their sensibilities or maybe they have too much on their hands. Regardless, is it too hard to add here? I feel like its easy to just take code from the other project.

https://github.com/TeamNewPipe/NewPipeExtractor/issues/779
https://github.com/TeamNewPipe/NewPipe/issues/6645

**Comment by stoponerr** [comment]
Please find a different app to ruin with your Chudtube

**Comment by LeonryLight** [comment]
> Please find a different app to ruin with your Chudtube

 I fail to see any disadvantages at all. A Rumble integration will be 100% optional. You will be able to use the app exactly like it was intended. Adding an optional plataform has no effect on anything you use right now on NewPipe.

**Comment by stoponerr** [comment]
> I fail to see any disadvantages at all. ... Adding an optional plataform has no effect on anything you use right now on Newpipe.

A lot of people don"t like using/supporting applications that work to platform fascists and bigots.

**Comment by LeonryLight** [comment]
> > I fail to see any disadvantages at all. ... Adding an optional plataform has no effect on anything you use right now on Newpipe.
> 
> A lot of people don"t like using/supporting applications that work to platform fascists and bigots.

How about anti war leftists that are censored on YouTube? Its sad to see how much of an useful idiot you can be and how ideologically possessed you are.

**Comment by stoponerr** [comment]
> How about anti war leftists that are censored on YouTube?
That's what PeerTube instances are for, but fedis mostly ban fascist instances so it filters itself without anything but community consent.

**Comment by Atemu** [comment]
You don't get banned from YT for being anti-war.

**Comment by polymorphicshade** [comment]
1. I have no problem with Rumble (or any other service) as I believe all platforms should be allowed, regardless of any controversial subjects.
2. I have no plans on adding any services, so I won't be doing this, but I will accept any merge request that adds this feature.
3. @LeonryLight as the template states, this is an extractor-related feature and thus not relevant to this fork.

**Comment by elvisoliveira** [comment]
@polymorphicshade Could you consider a merge of this branch with [brave](https://github.com/bravenewpipe/NewPipe)?

**Comment by DraconicNEO** [comment]
> @polymorphicshade Could you consider a merge of this fork with [brave newpipe](https://github.com/bravenewpipe/NewPipe)?

I second this, it would definitely be a good idea to use [BraveNewPipe](https://github.com/bravenewpipe) in this project in order to have as many services accessible to people.

**Comment by yoshimo** [comment]
https://github.com/InfinityLoop1309/AnimePipe changes could also be merged.

**Comment by DraconicNEO** [comment]
> https://github.com/InfinityLoop1309/AnimePipe changes could also be merged.

I do think that that will be a good idea, although I think it might be better to try and get Niconico and BiliBili support implemented upstream. I can't think of any reason why they wouldn't do it (unless they're japanophobic) since these sites to my knowledge aren't viewed poorly by Americans.

**Comment by DraconicNEO** [comment]
> https://github.com/InfinityLoop1309/AnimePipe changes could also be merged.

Watching all the NewPipe services become fragmented across different apps makes me wish more and more each day that there was a way we could forcefully take over the original repository and kick the original devs out because they are effectively ruining this project.

**Comment by polymorphicshade** [comment]
I won't be spending any of my limited free time adding support for different platforms, but I'm happy to accept any PRs that merge in support for different platforms.

**Comment by stoponerr** [comment]
A lot of people prefer not to support projects that explicitly platform fascists.

Aug 13, 2022, 05:41 by ***@***.***:
