### ISSUE TITLE
Enable playback of local files

### ISSUE THREAD

**Issue by barolo** [polymorphicshade/NewPipe#23]
I'm not sure if it would be better to ask upstream, if so just say.
NewPipe has a great 'skip silence' feature which I would love to use with everything but it doesn't even play files which it downloaded itself.

**Comment by polymorphicshade** [comment]
@barolo this should be brought up with the original NewPipe devs, since this would be a fairly larger and more "generic" change to the app (and not really SponsorBlock-specific), but I can look in to this just for the fun of it.

**Comment by barolo** [comment]
Guessed so, should I close this then? Or leave it for the time being, at least until any relevant info appears?

**Comment by polymorphicshade** [comment]
I'd say leave it open for now. If I decide it's too much work for what it's worth then I'll close it.

**Comment by barolo** [comment]
Upstream said no https://github.com/TeamNewPipe/NewPipe/issues/1501 ,kinda

**Comment by nadiration** [comment]
Wouldn't recommend this. The app is simple and great as it is bloating it with local videos and other unnecessary features will mess it up. Simplicity is the best and it's rare these days.

**Comment by barolo** [comment]
That's a purely subjective opinion, what you consider bloated might not be for others, it already plays videos ffs, most of it is on exo's side too. The app already has a support for couple of other services that I've never used.
Your concerns would be better suited for upstream, as this fork's raison d'être is a feature that was deemed unfit for the main one.

**Comment by barolo** [comment]
@polymorphicshade I've just found that AntennaPod, since latest version, supports playback of local files, including videos and has the silence skip feature [using exo too] and is the perfect companion for NewPipe.
So feel free to close this issue since I don't really feel like it's needed  in NP any longer.

**Comment by nadiration** [comment]
> @polymorphicshade 
> So feel free to close this issue since I don't really feel like it's needed in NP any longer.

You have the option to close your own issue there's a close button it's easier if you do it yourself

**Comment by barolo** [comment]
> > @polymorphicshade
> > So feel free to close this issue since I don't really feel like it's needed in NP any longer.
> 
> You have the option to close your own issue there's a close button it's easier if you do it yourself

learn to read

**Comment by nadiration** [comment]
> > > @polymorphicshade
> learn to read

I know. That's how i read your comment anyway sorry for the inconvenience i didn't mean it like that

**Comment by polymorphicshade** [comment]
I'm back from a small break. I don't plan on closing this for I think a built-in local player would be neat. 😃

**Comment by barolo** [comment]
Great :D I mean... it's kind of absurd that NewPipe can't play the files it downloaded itself...

**Comment by polymorphicshade** [comment]
@barolo actually I think there is a good reason for this. Their implementation of the exoplayer seems to be very heavily tied to streaming a remote uri. Simply reusing their implementation for a local uri would result in a lot of domino-effect changes and potentially sloppy workarounds.

It doesn't seem like a simple change... at least based on what I've looked at. This is the nature of software development...

**Comment by polymorphicshade** [comment]
Release [0.20.9 w/ SponsorBlock](https://github.com/polymorphicshade/NewPipe/releases/tag/0.20.9) now includes a built-in player for local playback with SponsorBlock support. Please report any issues you have with it in #30. 😊
