### ISSUE TITLE
"Download" button when holding on a video

### ISSUE THREAD

**Issue by flexagoon** [polymorphicshade/NewPipe#230]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

When I hold my finger on a video in a list (eg. on the What's New page or in a playlist), a menu pops up. I want a "Download" button to be in that list.

### Why do you want this feature?

It's very convenient sometimes, for example when I need to download many videos for a long trip. It's much quicker to do it this way instead of opening each video and clicking on the button. It also allows me to download videos while watching a different video.

### Why ist the feature relevant to this fork?

Upstream already has this feature, this fork doesn't for some reason

**Comment by Atemu** [comment]
> Upstream already has this feature, this fork doesn't for some reason

That's a bug then.

**Comment by polymorphicshade** [comment]
@flexagoon try out the latest version and see if you still have the same issue.

**Comment by flexagoon** [comment]
Yes, the issue no longer happens. Thanks.
