### ISSUE TITLE
As FYI - video loading issues reported from TNP Github

### ISSUE THREAD

**Issue by HairyMilkshakes** [polymorphicshade/NewPipe#232]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

See link

### Steps to reproduce the bug

See link

### Screenshots/Screen recordings

See link

### Additional information

https://github.com/TeamNewPipe/NewPipe/issues/8876

**Comment by PriyanshuPriyadarshi** [comment]
Newpipe sponsor block v0.23.2

**Video doesn't play it keep loading, maybe YouTube again change some code.**

**Comment by nklsfrt** [comment]
It's already been [fixed upstream.](https://github.com/TeamNewPipe/NewPipe/issues/8876)

**Comment by hyuaray** [comment]
Hello, I have the same issue and I tried different builds of the one's with sponsorblock and it doesn't load the video and description. I tried the app linked by nklsfrt and the newest build (23.3). I uninstalled newpipe before trying the other builds. I tried wiping cache and app storage.

**Comment by Atemu** [comment]
https://github.com/polymorphicshade/NewPipe/releases/tag/v0.23.3

**Comment by laurinneff** [comment]
It's not on IzzyOnDroid yet, does this need to be done manually and you forgot or do just need to wait?

**Comment by polymorphicshade** [comment]
@laurinneff I personally have nothing to do with IzzyOnDroid, so I suppose you'll have to wait.
