### ISSUE TITLE
throttling 

### ISSUE THREAD

**Issue by eladkarako** [polymorphicshade/NewPipe#235]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [ ] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

I'm still getting insane throttling,  
25-40kbps top.  
is there a way to get more information/debug from the android app (dump js player signature).  

I'm aware this fork has same extractor and I should probably open an issue there..  
any answer will be fine, and I'll close this asap.

**Comment by polymorphicshade** [comment]
@eladkarako You checked "I am not able to reproduce the bug with the same version of upstream NewPipe" as per the template. Did you actually try this with vanilla NewPipe?

**Comment by eladkarako** [comment]
crappy "og" newpipe has it as well.  

>I'm aware this fork has same extractor and I should probably open an issue there..
any answer will be fine, and I'll close this asap.
