### ISSUE TITLE
SponsorBlock section & other fork extras translation

### ISSUE THREAD

**Issue by nadiration** [polymorphicshade/NewPipe#24]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Since Team NewPipe blocked this great feature from the NewPipe app, they don't obviously put the SponsorBlock section strings in the translation project on Weblate. So it would be great if you put that small section (that's stuck in English when the app's language is switched) to a translation project on Weblate or any other way it can be translated to follow the app's language. 

#### Is your feature request related to a problem? Please describe it

Maybe. 

#### How will you/everyone benefit from this feature?

This feature will help people understand the feature more and make the most out of it. The app is currently translated into 81 languages and is gaining popularity. It's used by allot of people and people expect consistence in the app. 

Thank you for this great fork ❤️

**Comment by polymorphicshade** [comment]
I really don't want to bother setting up a translation website, but anyone is welcome to create pull requests with translated files.

Strings people can look at and/or translate can be found in: https://github.com/polymorphicshade/NewPipe/tree/sponsorblock/app/src/main/res/values-[CODE] where [CODE] is a language code (i.e. ar, be, it, etc...).

**Comment by nadiration** [comment]
@polymorphicshade i created  PR #28 to fix this. Check it out

**Comment by polymorphicshade** [comment]
@nadiration great, thanks for this! This will be in the next release. 😊
