### ISSUE TITLE
Merge With BraveNewPipe/Secondary Apk

### ISSUE THREAD

**Issue by seniorm0ment** [polymorphicshade/NewPipe#240]
Would love to see this merged with BraveNewPipe repo.
If not, merged as an "Alternative Version" so users can choose if they want NewPipe Sponsorblock, or the BraveNewPipexSponsorblock.

It's a repo of Newpipe with some added support for other free speech platforms such as Rumble. It honestly sucks needing two different apps just to view from those platforms. This would resolve that issue.

Like I said it's understandable if instead of merging, you provide a secondary apk that merges it so users can choose. Then it can be pushed to the F-Droid repo as well.

**Comment by polymorphicshade** [comment]
Please use the template for creating issues.

I have no problem supporting different platforms with my fork, however I won't be spending any of my limited free time adding support for different platforms. I'm happy to merge in an PRs that address this.
