### ISSUE TITLE
Thumbnail not loading for videos less than one minute

### ISSUE THREAD

**Issue by breaking-loss** [polymorphicshade/NewPipe#242]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1. Go to any shorts channel eg :Onevillage
2. Click on a video less than one minute

### Expected behavior

The expected behavior is that it  should load the thumbnail

### Actual behavior

The thumbnail does not load and shows a white -greyish screeen

### Affected Android/Custom ROM version

Havoc OS 3.9

### Affected device model

Redmi 6 pro

**Comment by breaking-loss** [comment]
[Uploading shorts_problem.zip…]()

Sorry the screenrecord wasn't uploading

**Comment by polymorphicshade** [comment]
@breaking-loss try out the latest version and see if you still have the same issue.

**Comment by breaking-loss** [comment]
The latest version doesn't have this bug
