### ISSUE TITLE
Merge with newest versions 

### ISSUE THREAD

**Issue by Jewmanji** [polymorphicshade/NewPipe#244]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

There is a new version in pre release on the issue page of newpipe.
Is it possible to merge with this version, or will we wait for official release. 

### Why do you want this feature?

Player slowdown from version 23

### Why ist the feature relevant to this fork?

Keep up to date

### Additional information

https://github.com/TeamNewPipe/NewPipe/issues/8890 is the link to the issue on the main branch

**Comment by polymorphicshade** [comment]
I only merge changes from the upstream master branch.
