### ISSUE TITLE
Sponsorblock segments don't appear

### ISSUE THREAD

**Issue by Nekothegamer** [polymorphicshade/NewPipe#248]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0 and previous

### Steps to reproduce the bug

1. go to a video with a sponsor on it
2. look at the progressbar

### Expected behavior

colored bars indicating sponsored and other types of segments should show on the video progressbar

### Actual behavior

 nothing appears and the progressbar looks normal

### Screenshots/Screen recordings

![Screenshot_20220927-161836~2](https://user-images.githubusercontent.com/112352776/192554255-9523b546-1a07-4ccb-a886-7ea00f06d90b.png)
![Screenshot_20220927-161506~2](https://user-images.githubusercontent.com/112352776/192554261-38c4f0ca-84b2-4f84-b58c-2f5e4b38f783.png)

### Affected Android/Custom ROM version

Android 11

### Affected device model

realme C25Y

### Additional information

as you can see on the screenshots, i activated sponsorblock (they're not in English but it is on)

**Comment by Atemu** [comment]
Try closing the app and opening it again.

**Comment by Nekothegamer** [comment]
it doesn't work at all, even if i close and reopen

**Comment by SebiTalent04** [comment]
Having the same issue on a Huawei Nova 5T with Android 10.

**Comment by elax93** [comment]
Same here, Samsung Galaxy Tab S8+ (Android 12L). The first time I set it up, it worked (on a long podcast video). But at some time during the same video the sponsorblock just stopped working and the markings disappeared .

**Comment by Atemu** [comment]
Verify that SB works in a browser, they're currently experiencing issues. https://status.sponsor.ajay.app/

**Comment by Nekothegamer** [comment]
> Does the issue still exists in latest version if not i.e. your issue is resolved then consider closing this issue.

yes it still persists, maybe the API link isn't the right one

**Comment by polymorphicshade** [comment]
@Nekothegamer I will re-open this if you can reproduce the problem with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.25.1).
