### ISSUE TITLE
Automation backup (schedule)

### ISSUE THREAD

**Issue by NSTAdventure** [polymorphicshade/NewPipe#249]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Hi sir mind to add automatic backup newpipe data?

### Why do you want this feature?

I don't want accidentally losing my newpipe data 

### Why ist the feature relevant to this fork?

I confused with official branch it's looks like official dev will not add it 
Since merge branch is have no feeedback:
https://github.com/TeamNewPipe/NewPipe/pull/3157

### Additional information

I already opening issues on official repo but then it's closed due to duplicate and someone else show me that merge branch

**Comment by Atemu** [comment]
> looks like official dev will not add it

They never rejected the idea. Not relevant to this fork.

You can follow upstream development [here](https://github.com/TeamNewPipe/NewPipe/issues/3558).

**Comment by NSTAdventure** [comment]
> > looks like official dev will not add it
> 
> They never rejected the idea. Not relevant to this fork.
> 
> You can follow upstream development [here](https://github.com/TeamNewPipe/NewPipe/issues/3558).

Closed for now idk how it's going all those related issues and merging branch is confusing as hell since new release isn't include those schedule backup
