### ISSUE TITLE
[Question] are there any vulnerabilities in this fork?

### ISSUE THREAD

**Issue by Snowden-rgb** [polymorphicshade/NewPipe#25]
I am a genuine fan of this fork and newpipe, but i do want to ask if any there is any downside of this fork, i mean are there any possible privacy concerns with adding sponsorblock?

**Comment by nadiration** [comment]
They collect some data like your ip and something like that 'to know how many people are using the service and see who contributes the most' you should read their [privacy policy](https://gist.github.com/ajayyy/aa9f8ded2b573d4f73a3ffa0ef74f796)

**Comment by Snowden-rgb** [comment]
ok thanks
