### ISSUE TITLE
Downloading videos has become worse

### ISSUE THREAD

**Issue by breaking-loss** [polymorphicshade/NewPipe#250]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Go to a video
2. Download it
3. Let your WiFi go below 0 b/s

### Expected behavior

The video should be automatically resumed when the WiFi comes back . This was available in the older versions .

### Actual behavior

When the WiFi goes below 0b/s the download gets stopped . Even if the WiFi comes back the video doesn't get resumed .I have to go to downloads , pause the video and resume it in order to resume downloading .

### Affected Android/Custom ROM version

Android 12/Corvus OS 3.0

### Affected device model

Redmi 6 pro

### Additional information

I have a shit internet

**Comment by breaking-loss** [comment]
![Screenshot_20221001-084425_NewPipe SponsorBlock](https://user-images.githubusercontent.com/110153010/193384354-0f3cf56f-fe51-4f22-93cd-fb3d54bf9d63.png)

This is the proof

**Comment by Atemu** [comment]
How does upstream NewPipe behave here?

**Comment by breaking-loss** [comment]
From what I tested newpipe auto downloads when the WiFi gets reduced to 0b/s but if the internet is switched off and turned back on it doesn't auto download .

**Comment by breaking-loss** [comment]
On another topic I get like 2mb download speed when I use newpipe but when I use newpipe sponsor block I get less than 1 mb .Is it related to servers ?

**Comment by breaking-loss** [comment]
After further testing newpipe also auto downloads after the internet is switched off .

**Comment by breaking-loss** [comment]
> It also behaves the same way in new pipe see this [thread][TeamNewPipe#962](https://github.com/TeamNewPipe/NewPipe/issues/962) The issue is with the downloader itself

My bad when I tested it it worked fine and there wasn't any issues on github . Sorry for wasting the time . I apologies for not closing the issue as I only saw the comment today.
