### ISSUE TITLE
Media player crash

### ISSUE THREAD

**Issue by NSTAdventure** [polymorphicshade/NewPipe#251]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Open newpipe and any video
2. Watch video till end, minimize, and reopen the video
3. Media player freeze and causing error

### Expected behavior

No error 

### Actual behavior

Crash

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ ID
* __Content Language:__ id
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux realme/RMX2030/RMX2030:10/QKQ1.200209.002/1605146661:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{4d9991a u0 org.polymorphicshade.newpipe/org.schabi.newpipe.player.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7853)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10 Stock Rom 

### Affected device model

Realme 5i

### Additional information

Official dev is horsemen of annoyance i said i don't have a cats :-(

Triggered on your fork lazy to reproduce in vanila so i report here sorry about that 🙏😅

**Comment by polymorphicshade** [comment]
> - [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).

> Triggered on your fork lazy to reproduce in vanila so i report here sorry about that 🙏😅

Please understand that by saying this while also acknowledging this item in the template, you are actively choosing to waste our time.

Have a little respect for our work please.

**Comment by NSTAdventure** [comment]
> Please understand that by saying this while also acknowledging this item in the template, you are actively choosing to waste our time.\n\nHave a little respect for our work please

Wait in readme is clearly said that report fork issues should be done here instead in upstream unless you can reproduce this in vanilla or upstream

I did that why you still can say i waste your time and not respecting your work?

**Comment by polymorphicshade** [comment]
@NSTAdventure you said you were too lazy to try to reproduce the bug on vanilla NewPipe.

Issues posted to this fork are meant to be fork-specific.

If an issue can be reproduced upstream, then it is a waste of time for me to look in to it, since that means I would have to constantly merge and "re-fix" the problem as I keep this fork up-to-date with the upstream branch.

By admitting you are too lazy to try to reproduce it upstream, you are admitting that you don't care about how much time I might spend fixing something that should be fixed by the upstream devs.

**Comment by NSTAdventure** [comment]
> @NSTAdventure you said you were too lazy to try to reproduce the bug on vanilla NewPipe.
> 
> Issues posted to this fork are meant to be fork-specific.
> 
> If an issue can be reproduced upstream, then it is a waste of time for me to look in to it, since that means I would have to constantly merge and "re-fix" the problem as I keep this fork up-to-date with the upstream branch.
> 
> By admitting you are too lazy to try to reproduce it upstream, you are admitting that you don't care about how much time I might spend fixing something that should be fixed by the upstream devs.

Ah i see 
I owe you apologize for this mistake sir 
I try my best to not do that again 🙏

Regards
NST_Adventure
