### ISSUE TITLE
Cut sponsors from downloaded videos/audio

### ISSUE THREAD

**Issue by JeFi2** [polymorphicshade/NewPipe#26]
I only use NewPipe to download videos as audio and listen to them later. It would be nice if that also worked with SponsorBlock.

I don't know if this is even possible but there's a youtube-dl fork that does this so one can hope.

**Comment by polymorphicshade** [comment]
I'm currently working on this; it's related to #23.

**Comment by polymorphicshade** [comment]
Release [0.20.9 w/ SponsorBlock](https://github.com/polymorphicshade/NewPipe/releases/tag/0.20.9) now includes a built-in player for local playback with SponsorBlock support. Please report any issues you have with it in #30. 😊
