### ISSUE TITLE
Add support for  volume amplification

### ISSUE THREAD

**Issue by Master2050** [polymorphicshade/NewPipe#262]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Add an option to boost volume to 200% or if possible 300% 

### Why do you want this feature?

Useful for devices with low volume speakers or if there is a lot of commotion and you still want to watch some video but don't have the headphones or headsets around.

### Why ist the feature relevant to this fork?

[Rejected proof link shown in screenshot](https://github.com/TeamNewPipe/NewPipe/issues/4879#issuecomment-728836635) 
<img alt="Screenshot_2022-10-21-20-51-52-14" src="https://user-images.githubusercontent.com/28833686/197231396-352828ab-f8ea-4f1c-a407-f9de000ef03d.png" height=600 />

### Additional information

Very common feature in almost every modern video player

**Comment by polymorphicshade** [comment]
I see no reason to spend time implementing this feature since there are plenty of other apps that do the same thing globally.
