### ISSUE TITLE
Add multi band equalizer for native player

### ISSUE THREAD

**Issue by Master2050** [polymorphicshade/NewPipe#263]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Here is a visual example

<img alt="Screenshot_2022-10-19-10-45-30-23_deca60f65c681d0bc43599a3c6f91501" src="https://user-images.githubusercontent.com/28833686/196603317-10f2cf3a-fd46-42a4-902f-356cdf5678cb.png" height=600 />

Would be nice if reverb and bass boost is also added.

### Why do you want this feature?

I believe it will be a nice addition and would be useful for many

### Why ist the feature relevant to this fork?

[Link for reference to rejection of feature](https://github.com/TeamNewPipe/NewPipe/issues/7118) 

<img alt="Screenshot_2022-10-21-20-58-58-19" src="https://user-images.githubusercontent.com/28833686/197232893-d252d4aa-72ee-4495-9cbd-5196b6b11de4.png" height=600 />

**Comment by polymorphicshade** [comment]
I don't see any good reason to implement a feature like this, since there are plenty of other apps that can do this.
