### ISSUE TITLE
Settings and database import from newpipe bug

### ISSUE THREAD

**Issue by killerrook** [polymorphicshade/NewPipe#266]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Open official new pipe app 
2. Export settings by clicking content>export database
3. Open new pipe sponsor block app 
4. Import database

Note:
 1. It doesn't matter whether you choose to import setup database only or database with settings
2. It doesn't matter if you enable sponsor block before or after the import

### Expected behavior

Database should be imported and app should work fine

### Actual behavior

Sponsor block stops working entirely

### Affected Android/Custom ROM version

Color OS v6.0(android 9)

### Affected device model

Oppo Realme 1 CPH1861

### Additional information

Sponsor block and other features work as intended if nothing is imported.

**Comment by Atemu** [comment]
Well it probably disables SponsorBlock in the settings since those settings aren't set in regular NewPipe and off by default in ours.

**Comment by Atemu** [comment]
SB is currently experiencing issues FYI: https://status.sponsor.ajay.app/
