### ISSUE TITLE
Unable to import subscription exported by official newpipe

### ISSUE THREAD

**Issue by killerrook** [polymorphicshade/NewPipe#267]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Export subscription using official new pipe
2. Try to import the aforesaid subscription with new pipe sponsor block 
3. The file picker won't even let you pick the exported file(maybe something wrong with extension or something just guessing)

### Expected behavior

Allows me to import subscription

### Actual behavior

Doesn't let me pick the exported file

### Affected Android/Custom ROM version

Color OS v6.0(android 9)

### Affected device model

Oppo Realme 1 CPH1861

**Comment by Atemu** [comment]
Does this work in upstream NewPipe?
