### ISSUE TITLE
Is the video downloaded with sponsorblock segment trimmed or entire full video?

### ISSUE THREAD

**Issue by Master2050** [polymorphicshade/NewPipe#269]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

If entire full video is downloaded I will consider opening a feature request here.

**Comment by polymorphicshade** [comment]
Downloaded videos do not have anything cut out of them. The build-in player just looks up a cache of SponsorBlock segments (downloaded with the video) to skip.

I have no plans on implementing a way to cut out segments from downloaded videos.
