### ISSUE TITLE
Sponsorblock not working

### ISSUE THREAD

**Issue by PassionateG1t** [polymorphicshade/NewPipe#270]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Enable sponsorblock
2. Enter any video with sponsors

### Expected behavior

Sponsorblock successfully detects and skips unwanted content 

### Actual behavior

Sponsorblock does f*ck all 🤭

### Screenshots/Screen recordings

<img alt="screenshothwgwh" src="https://user-images.githubusercontent.com/107609269/197359281-636076d9-0508-432d-b4c4-953277ad0081.jpg" height=600 />

### Affected Android/Custom ROM version

Android 12

### Additional information

Sponsorblock is successfully sending network requests. It was working a week ago (?)
I erased cache, no results.

**Comment by suburbanbourbon** [comment]
I am able to reproduce the same issue on the latest version on my device

**Comment by Atemu** [comment]
Does it work in a browser? Sponsorblock is experiencing issues: https://status.sponsor.ajay.app/

**Comment by suburbanbourbon** [comment]
It is working for me. Tested on Kiwi Browser

**Comment by kezzbracey** [comment]
Same issue on my devices, phone and tablet, Android 12.

**Comment by gsture** [comment]
I agree, sponsorblock is not working at the moment.

**Comment by bizz91** [comment]
Its not working here either.

**Comment by l3oxy** [comment]
I had to do the following to get it working for me on version 0.24.0 on Android 11:

Settings > SponsorBlock > API URL
Click the red button "?" on the right.
Click "USE OFFICIAL" .
Click "OK".

Settings > SponsorBlock
Ensure that you have enabled "Skip Sponsors".

Settings > SponsorBlock > SponsorBlock Categories
Enable everything (or at least everything that you want).

**Comment by Atemu** [comment]
Just close it yourself.

**Comment by johnnydepup** [comment]
It's an old issue, but I have never been able to get Sponsor block working on for me. The app works fine and the videos play, but none of the sponsors ever got skipped till now. 
I had used the app once last year. It didn't work then, and I removed it and used regular New pipe instead. I have reinstalled it again, this time in a Graphene phone, it still does not work. 

I have Sponsor block URL set, enable the Skip option. I neither see the segments displayed on the timeline, nor any of it gets skipped. 
If I play the same video on my browser with the Sponsorblock plugin, those segments are skipped as expected. 
Is there any extra configuration I am missing here?

**Comment by suburbanbourbon** [comment]
@durgaswaroop What is the API URL that you have set? And in the SponsorBlock settings menu in "SponsorBlock Categories" have you enabled Sponsor (and whatever other segments that you want to skip)? And I hope you are using the latest version i.e., 0.25.1
