### ISSUE TITLE
Add a disable sponsorblock switch 

### ISSUE THREAD

**Issue by killerrook** [polymorphicshade/NewPipe#271]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

If you have to disable all categories(sponsors, intro/outro, etc) of sponsor block you have to remove the api link manually else the player will still fetch sponsor block segments from the server which will result in extra mobile data consumption for no good reason. Currently only skip sponsor toggle is available which only toggles the sponsor category in all categories. 

The toggle should be also available somewhere in the video player 'request for information' screen for ease of access.

### Why do you want this feature?

Mobile data efficiency. Also it's time consuming to remove api link manually. 

### Why ist the feature relevant to this fork?

Sponsor block

**Comment by Midou36O** [comment]
> The toggle should be also available somewhere in the video player 'request for information' screen for ease of access.

Fyi there is a disable sponsorblock button when you go full screen and press the arrow on the top right :)

**Comment by Atemu** [comment]
@Midou36O does that still contact the sponsorblock servers? That's what @Master2050 is concerned about.

**Comment by Midou36O** [comment]
From what i can see no, it just stops skipping segments. But i do believe that if you're using this fork you're supposed to want that feature, and for cellular data, i'm pretty sure that videos are more concerning than connecting to a database (O.o)

**Comment by Atemu** [comment]
@Midou36O they might be listening to audio. Though even then sponsorblock fetches would be of no concern.
