### ISSUE TITLE
Doubleclick tracking

### ISSUE THREAD

**Issue by stemy2** [polymorphicshade/NewPipe#275]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

I'm currently using an utility to detect and blick trackers that are inside the apps. The said utility detected a tracker named "Google Doubleclick" inside "newpipe x sponsorblock". Is it normal ?

**Comment by polymorphicshade** [comment]
Do you get the same results when checking vanilla NewPipe?
Last I recall reading, NewPipe sends spoof data to Google so there shouldn't be any actual real tracking going on.

If you see any tracking-related reports about NewPipe (or my fork), see [this post on Reddit](https://www.reddit.com/r/NewPipe/comments/y62sd9/why_tf_is_google_tracker_installed_in_newpipe_o/).
