### ISSUE TITLE
Nothing in Chanels and nothing new in fead

### ISSUE THREAD

**Issue by Jjjggh** [polymorphicshade/NewPipe#277]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1 go to channel 
2 nothing in there
<img alt="Screenshot_20221101-171946_NewPipe SponsorBlock" src="https://user-images.githubusercontent.com/102470504/199256699-af877389-b5ee-4161-9115-f128f5e16143.jpg" height=600 />

Or 
1 refresh fead 
2Nothing new although there actually is but only appears if u search manually 
<img alt="Screenshot_20221101-172004_NewPipe SponsorBlock" src="https://user-images.githubusercontent.com/102470504/199256612-6396d697-ff69-4d37-ba8f-a87e145f3e11.jpg" height=600 />
<img alt="Screenshot_20221101-172004_NewPipe SponsorBlock" src="https://user-images.githubusercontent.com/102470504/199256636-c0d690f8-9111-40dc-84b4-7a690375508d.jpg" height=600 />
<img alt="Screenshot_20221101-171949_NewPipe SponsorBlock" src="https://user-images.githubusercontent.com/102470504/199256711-0c83e44c-1254-4004-8506-0ee54e8a6261.jpg" height=600 />

### Expected behavior

Have the videos up to date 

### Actual behavior

Nothing in the channels at all and nothing in the feed 

### Screenshots/Screen recordings

<img alt="Screenshot_20221101-171946_NewPipe SponsorBlock" src="https://user-images.githubusercontent.com/102470504/199257044-f79990d3-0776-481b-adbd-4417fe803b14.jpg" height=600 />
<img alt="Screenshot_20221101-171949_NewPipe SponsorBlock" src="https://user-images.githubusercontent.com/102470504/199257053-e0cbe7c8-168c-4bdd-b579-8f84491dc8a9.jpg" height=600 />
<img alt="Screenshot_20221101-171955_NewPipe SponsorBlock" src="https://user-images.githubusercontent.com/102470504/199257057-13cff253-6d89-4ea6-bc96-b1e3402e9bc8.jpg" height=600 />
<img alt="Screenshot_20221101-172004_NewPipe SponsorBlock" src="https://user-images.githubusercontent.com/102470504/199257062-b0e55cca-0e97-4b54-bb99-f9d06b2c094d.jpg" height=600 />

### Affected Android/Custom ROM version

Android 12 one ui 4 

### Affected device model

Samsung galaxy a 51

**Comment by ccateni** [comment]
It's an issue with the main newpipe too. The new layout is causing issues with newpipe getting videos.

**Comment by bizz91** [comment]
Happening here as well.

**Comment by ccateni** [comment]
Problem is, we have to wait for NewPipe to fix the issue with a new version before the sponsorblock version can be fixed.

**Comment by Tallefer** [comment]
a temporary and imperfect workaround copied from relevant issues
https://github.com/TeamNewPipe/NewPipe/issues/9263
https://github.com/TeamNewPipe/NewPipe/issues/9264

> go to `Feed` > Click on `❔` icon on top right corner> Click on `Enable fast mode` > Reload the feed.
Note that video length is not shown while using this method.

**Comment by Jjjggh** [comment]
> a temporary and imperfect workaround copied from relevant issues
> https://github.com/TeamNewPipe/NewPipe/issues/9263
> https://github.com/TeamNewPipe/NewPipe/issues/9264
> 
> > go to `Feed` > Click on `❔` icon on top right corner> Click on `Enable fast mode` > Reload the feed.
> Note that video length is not shown while using this method.

 
I tried both modes multiple times but nothing happened 
Do u know anyway else to fix it

**Comment by Tallefer** [comment]
> I tried both modes multiple times but nothing happened Do u know anyway else to fix it

In my case I fired a fast refresh once and it seemed like nothing is happening, but the second time it worked. or perhaps it was just a display glitch - try scrolling down to ~yesterday (the time when yt layout has changed)
also some currently 100% active videos/streams are not showing for me in this mode so ymmv.

**Comment by polymorphicshade** [comment]
Read the template next time please.
