### ISSUE TITLE
New videos failing to be found

### ISSUE THREAD

**Issue by zoomerjoey** [polymorphicshade/NewPipe#278]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

Trying to refresh the what's new page will not pull any new videos

### Expected behavior

New videos should be found since I know someone should have uploaded something in the last 24 hours

### Actual behavior

No new videos found

### Screenshots/Screen recordings

<img alt="Screenshot_20221102-100702" src="https://user-images.githubusercontent.com/96153001/199525963-89f09141-88dc-4cf4-9a5a-ed0f7049e7ac.png" height=600 />

### Affected Android/Custom ROM version

Android 12

### Affected device model

Google pixel 3a

**Comment by NoPlagiarism** [comment]
Waiting for TeamNewPipe/NewPipeExtractor#944

**Comment by Atemu** [comment]
Please read the template. It's there for a reason.

**Comment by NoPlagiarism** [comment]
@Atemu tnx for mentioning it
![image](https://user-images.githubusercontent.com/37241775/199537523-79dffe70-5332-4eb0-b158-b6913c1ee97b.png)
