### ISSUE TITLE
SponsorBlock for downloaded videos

### ISSUE THREAD

**Issue by Nikhar14** [polymorphicshade/NewPipe#280]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I am not very good at technical. So basically I would like to suggest a feature such that SponsorBlock could be used on downloaded videos. This could be implemented by playing the downloaded videos within the Newpipe app and with just the small internet connection (as the video would be already downloaded), look for sponsorblock sections and use them to skip over segments.

If somebody could better describe the issue, please close this one and create with better technical explaination.

PS: The same works in Vanced, for downloaded videos, since the video plays within the app, the sponsorblock works on downloads.

### Why do you want this feature?

This will be a very useful feature as sponsorblock could then be used on downloaded videos as well.

### Why ist the feature relevant to this fork?

As it is specifically related to SponsorBlock

**Comment by polymorphicshade** [comment]
See: https://github.com/polymorphicshade/NewPipe/issues/30
