### ISSUE TITLE
SponsorBlock not working on downloaded videos

### ISSUE THREAD

**Issue by Nikhar14** [polymorphicshade/NewPipe#282]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

Enable Local Player (alpha) from "Extras" settings
Download any video
Go to Downloads and play the video
SponsorBlock wont skip, identify or color-code segments (even with Internet connected)

### Expected behavior

Sponsor segments should perform same as playing video by going on any subscription or feeds

**Comment by polymorphicshade** [comment]
@killerrook is right, but as an FYI to @Nikhar14, SponsorBlock does work in the local player but there are no colored segments.
If you downloaded a video before enabling SponsorBlock, you will have to re-download the video to refresh the associated segments in the database.
