### ISSUE TITLE
how to add new segments in newpipe

### ISSUE THREAD

**Issue by komals1** [polymorphicshade/NewPipe#283]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

want to know how to add a new segments

**Comment by Atemu** [comment]
You don't. This feature is not implemented and probably won't be. Submit them on a computer where you can put in the times accurately.

**Comment by polymorphicshade** [comment]
See: https://github.com/polymorphicshade/NewPipe/discussions/260
