### ISSUE TITLE
Sponsorblock during background playback

### ISSUE THREAD

**Issue by multichoyce** [polymorphicshade/NewPipe#29]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Skip sponsor segments during background playback

#### Is your feature request related to a problem? Please describe it
Kinda? Sponsorblock doesn't work while in background playback mode

#### Additional context
For now i have to use vanced for bg music and ymusic doesn't have sponsporblock implemented yet

#### How will you/everyone benefit from this feature?
It would be super useful for skipping non-music sections in music videos and sponsors during podcasts

**Comment by polymorphicshade** [comment]
Background skipping should be working... have you checked the categories to see which segment types are skippable? Not all of them are enabled by default.

**Comment by multichoyce** [comment]
You're right, it does work, I did have all the segments enabled. Managed to test it on another device to makes sure, will nuke my install and start over

**Comment by multichoyce** [comment]
Update: Works fine on aosp pie but couldn't get it to work on an s8 on pie. tried everything, somehow managed to work once but I went into settings again to switch off watch history and it wouldn't again. Started  over and couldn't get it working in background again. If i had to guess it's probably just a "me" problem.
Thanks for the response wouldn't have tried it on another device otherwise

**Comment by polymorphicshade** [comment]
Interesting... I'll re-open this issue so it's easier for others to find and possibly report any similar experiences they have.

Strange that the behavior could be different on hardware variations with the same android version. If I had to guess it might be related to how those respective devices handle power saving. Maybe it has to do with non-android-specific software limiting functionality of background apps?

**Comment by multichoyce** [comment]
Tested abit more, I was going hoping it would be something simple aswel. I always have my background music stuff allowed from battery and data saver. It won't skip while i have the app open and i chose play in background which is what makes me so sure it's not that, but it working fine on another device while no one has such issues is making me doubt myself, might have to reset device at some point

**Comment by drcassar** [comment]
I'm on LineageOS 14.1 (so android 7.1.2). It sure is old, but I'm getting the same issue as @multichoyce. When playing in the background it won't skip. Doesn't matter if the app is on the screen or not. However, it works like a charm when actually watching the video. Tested on the latest build (0.20.10).

**Comment by everykenyan** [comment]
@drcassar I have tested this and it seems irrelevant to the OS or device.
It seems to work when playing a single video, but you can't just hit the background playback without atleast starting visual playback, and in a playlist mode it will keep skipping the segment of the first video only even if it's onscreen with video playing, instead of loading segments for the subsequent videos.., I recorded my screen to show the behaviour, sorry for no audio, hope it's still useful
[Background playlist audio](https://files.catbox.moe/9o73yq.mp4)
[Foreground Playlist video](https://files.catbox.moe/etyn1n.mp4)

**Comment by polymorphicshade** [comment]
Yup... looking in to it, seems both the background player and popup player never query the SponsorBlock segments. I'll get on fixing that.

**Comment by polymorphicshade** [comment]
@multichoyce @drcassar @everykenyan give this [APK](https://github.com/polymorphicshade/NewPipe/files/6017301/newpipe_x_sponsorblock_debug.zip) a shot and let me know if you are still having issues.

**Comment by drcassar** [comment]
Hi @polymorphicshade, I've tested the new APK and here are the results:

- It works if you start playing with video

**Comment by drcassar** [comment]
Thanks @polymorphicshade. I've tested the new APK and here are the results:

- It works if you start playing with video playback;
- It works if you start playing just the audio in the background;
- It stop skipping if you open the video playback and change to background audio;
- It also stop skipping if you open the background audio and change to video playback.

**Comment by polymorphicshade** [comment]
@drcassar ...how about this [APK](https://github.com/polymorphicshade/NewPipe/files/6018529/newpipe_x_sponsorblock_debug.zip)?

**Comment by multichoyce** [comment]
This one you just posted is working perfect, I didnt have a go at the previous debug one but I tried to recreate the issues I've had and those posted by drcasser, no problems so far. Thank you

**Comment by drcassar** [comment]
Working perfectly for me now. Thanks a lot @polymorphicshade!

**Comment by polymorphicshade** [comment]
Good to hear fellas. Turns out I needed to move the SponsorBlock API call from the visual video detail view over to the more "internal" MediaSourceManager class. Not 100% sure it's in the correct spot, but so far it looks like it is.

**Comment by polymorphicshade** [comment]
This should now be fixed in the latest release.

**Comment by everykenyan** [comment]
Working beautifully @polymorphicshade , that was really fast man :) Thanks
