### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by tvnmguy** [polymorphicshade/NewPipe#293]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Use new tweaked NewPipe logo with SponsorBlock icon instead of vanilla NewPipe logo

<img alt="IMG_20221227_122252" src="https://user-images.githubusercontent.com/116799295/209659777-f82e9256-d38f-41a9-bade-0f6c8259217d.jpg" height=600 />

### Why do you want this feature?

Which is very useful to distinguish between NewPipe and NewPipe SponsorBlock.

![IMG_20221227_123525](https://user-images.githubusercontent.com/116799295/209659988-711c739b-728c-49d6-acc9-1bf81b9bd271.jpg)

### Why ist the feature relevant to this fork?

This icon is more meaningful for 'NewPipe SponsorBlock' title.

### Additional information

Sorry, I don't have the svg file of the logo because the logo throughout edited with the help of mobile editing app.

**Comment by polymorphicshade** [comment]
Thanks, but we already have a new icon (for the tubular rebranding).
