### ISSUE TITLE
Download videos with sponsor part removed

### ISSUE THREAD

**Issue by breaking-loss** [polymorphicshade/NewPipe#294]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

When downloading a video provide an option to download the video without sponsor bits . Seal https://github.com/JunkFood02/Seal by @JunkFood02 does this . 

### Why do you want this feature?

I download videos for offline playback and the sponsors annoy me

### Why ist the feature relevant to this fork?

Newpipe doesn't support sponsor block so I doubt they would support downloading without sponsors

**Comment by polymorphicshade** [comment]
Actually you can watch downloaded videos with segments "removed" (auto-skipped) by the new built-in player.
See: https://github.com/polymorphicshade/NewPipe/issues/30

**Comment by breaking-loss** [comment]
> Actually you can watch downloaded videos with segments "removed" (auto-skipped) by the new built-in player. See: #30

I have older videos which were copied to the download folder but aren't recognized , some of them were removed from YouTube also . Downloading without sponsor part would be great for this two situations .

**Comment by Deathshot1** [comment]
El 7 abr. 2023 1:22 a. m., breaking-loss ***@***.***> escribió:

Actually you can watch downloaded videos with segments "removed" (auto-skipped) by the new built-in player. See: #30

I have older videos which were copied to the download folder but aren't recognized , some of them were removed from YouTube also . Downloading without sponsor part would be great for this two situations .
