### ISSUE TITLE
App Crash when Screen Auto rotation is off

### ISSUE THREAD

**Issue by aldrinjenson** [polymorphicshade/NewPipe#297]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Make sure Auto rotation is turned off in device
2. Play any video
3. App crashes with the whole UI being rotated to landscape mode
4. Open app again and play any video
5. The UI changes automatically to landscape mode and App crashes again
6. Turn auto rotation on
7. Open app again and play a video
8. Now video plays

### Expected behavior

- The app shouldn't crash when screen rotation is off
- The app shouldn't erratically adjust rotation UI without the device actually being rotated physically
- The app should automatically adjust layouts based on auto rotation

### Actual behavior

- App crashes when video is played with auto rotation 
- If the auto rotation was turned on initially and then turned off after loading newPipe, the UI automatically turns to landscape mode (even if the phone is held in portrait mode only) and then video plays fine
- If the auto rotation is turned off before the app was loaded, the app crashes when a video is played

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/53407417/214132494-b3acfeb2-c9bf-4448-959e-b1c899f0a312.mp4

## Exception
* _User Action:_ ui error
* _Request:_ ACRA report
* _Content Country:_ IN
* _Content Language:_ en-IN
* _App Language:_ en_IN
* _Service:_ none
* _Version:_ 0.24.1
* _OS:_ Linux Nokia/Phoenix_00WW/PNX_sprout:11/RKQ1.200906.002/00WW_6_210:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$handleResult$23(VideoDetailFragment.java:1626)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$kvbSCZYpk1eZXvjw0VQVcbHCIUo(Unknown Source:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda38.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)

</details>
<hr>

### Affected Android/Custom ROM version

Android 11

### Affected device model

Nokia 8.1

### Additional information

Please note that in the whole of screen recording, the phone was held in portrait mode only in my hand. The whole UI shifting to landscape mode was solely due to the software (Newpipe sponsorblock). 
This occurs only with Newpipe sponsorblock.

I found #216  issue. But it's not exactly the same, so I'm creating this new one here.
Feel free to close this if you think this belongs under that one.
Thanks.

**Comment by polymorphicshade** [comment]
I believe this is now fixed.

I will re-open this issue if you can reproduce this issue with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.25.1).
