### ISSUE TITLE
How can I reveal the dislike count ?

### ISSUE THREAD

**Issue by Shocoo** [polymorphicshade/NewPipe#298]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

As I said, I don't see any dislike count under the video. I the description of the fork, it is written " A fork of NewPipe with SponsorBlock and `Return YouTube Dislike functionality`". Can you help me to see it ?

**Comment by Atemu** [comment]
Settings > Extras > Show disklike count.

**Comment by Shocoo** [comment]
Thank you 😄
