### ISSUE TITLE
Add More Filtering Options (upload date, duration,etc)

### ISSUE THREAD

**Issue by RA1-Asur** [polymorphicshade/NewPipe#304]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

In the vanilla Newpipe , there is no feature to "sort" videos by duration, upload date, relevance, view count, live ,etc. But in an another fork of Newpipe "Bravenewpipe" , this feature is available. 
<img alt="Screenshot_2023-02-11-19-04-41-243_com github bravenewpipe" src="https://user-images.githubusercontent.com/123820449/218265561-727f267c-e625-4a32-a64b-a21c44567c85.jpg" height=600 />
Can you add this feature to "Tubular" and you can give him the credits. Is this anyhow possible??

### Why do you want this feature?

Its frequently useful for users and it gives more choices to the users.

### Why ist the feature relevant to this fork?

‎‎

### Additional information

I'm linking the bravenewpipe fork
https://github.com/bravenewpipe/NewPipe

**Comment by Atemu** [comment]
Why isn't this feature in upstream NewPipe? We only care about features upstream explicitly does not want due to ideological reasons.
