### ISSUE TITLE
UI crashes when I try to play any video

### ISSUE THREAD

**Issue by erfirya** [polymorphicshade/NewPipe#311]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

1. Open newpipe x sponsor block
2. Tap on a video

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.0
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$handleResult$46(VideoDetailFragment.java:1550)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$TSo6QiHfELHtkEIc_NXVo32oCuA(VideoDetailFragment.java:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda54.run(R8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13 / crDroid 9.2

### Affected device model

Xiaomi POCO X3 NFC

**Comment by polymorphicshade** [comment]
I'm sorry to say this isn't enough information for me. Everything seems to work fine on my end.

I will re-open this issue if you can reproduce this issue with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.25.1).
