### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by lsomm** [polymorphicshade/NewPipe#324]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Hey, I love this project and the time it is saving me! You are doing an awesome job and I would like to give something back. Is there a way for me to donate to the project or the people involved directly? 
I have no project expectations for my donation, I just want to buy you a coffee or beer :smiley:.

Maybe you might even consider a donation page at liberapay or opencollective, where other small projects are.

Best,

Luca

**Comment by polymorphicshade** [comment]
I really do appreciate the sentiment, but I would much rather have donations go towards the upstream devs:
https://newpipe.net/donate/
