### ISSUE TITLE
Sponsorblock isn't applied in audio-only playback ('background' player)

### ISSUE THREAD

**Issue by ghost** [polymorphicshade/NewPipe#326]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.25.1, potentially every version of the app

### Steps to reproduce the bug

1. enable the Sponsorblock categories in the app settings
2. open a YT video containing Sponsorblock-recognized sponsorship (e.g. `https://www.youtube.com/watch?v=k7wnNt65lcE`)
3. play and inspect how the promotion segments are skipped
4. switch to the 'background' (audio-only) player and inspect how the promotion segments **are not** skipped

### Expected behavior

The promotion portions present in the Sponsorblock database are skipped in identical fashion with both the video and 'background' player.

### Affected Android/Custom ROM version

Android 13 / LineageOS 20

**Comment by Atemu** [comment]
Duplicate of https://github.com/polymorphicshade/NewPipe/issues/257.

**Comment by ghost** [comment]
> Duplicate of #257.

Sorry, I searched for issues with `audio` in their title.
