### ISSUE TITLE
Option to disable "Sorry something went wrong" pop-up message. 

### ISSUE THREAD

**Issue by Fatcakes** [polymorphicshade/NewPipe#33]
I have had this pop-up since the .2x update and it's very annoying. I thought whatever this issue was would have been fixed at this point despite reporting the official projects git. Maybe put it in the extras. I knows it not at the top of the list but I would appreciate it. The original projects devs are never gonna fix the issue so giving us the option would be great. The app works fine despite the errors. It can just as easily be turned back on to report the bugs in the event that it's needed. Thanks again @polymorphicshade. And, I apologize in advance if maybe I'm just an idiot and this option is already in the app and I just didn't see it.

**Comment by polymorphicshade** [comment]
Are you talking about the exception message pop up? I believe 99% of the cases I've seen are related to the Extractor (not part of my fork).

I could add an option in Extras to completely disable prompts like that, but it would have to come with a warning that doing so could hide potentially severe errors.

**Comment by Fatcakes** [comment]
@polymorphicshade yes exactly. Please do it.

**Comment by polymorphicshade** [comment]
Give this [APK](https://github.com/polymorphicshade/NewPipe/files/5992713/apk.zip) a shot and let me know what you think. 😊

**Comment by Fatcakes** [comment]
@polymorphicshade its been working for me without issue my friend. 🙏😊

**Comment by polymorphicshade** [comment]
@Fatcakes dope, then this will be in the next release.
