### ISSUE TITLE
Add Newpipe Sponsoblock to Accrescent app store

### ISSUE THREAD

**Issue by guilamoff** [polymorphicshade/NewPipe#331]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Could you add your NewPipe Sponsoblock application to the new Accrescent application store.
Accrescent is an open-source, next generation application store and is very easy to use. Here is the link https://accrescent.app/features

Sincerely

### Why do you want this feature?

Accrescent is a new app store with a focus on security and I think your app fits right in.

### Why ist the feature relevant to this fork?

The basic newpipe application is excellent but it does not have sponsoblock

**Comment by matchboxbananasynergy** [comment]
NewPipeXSponsorblock, for the same reasons as NewPipe, is unlikely to be eligible for inclusion in the store right now.

I've detailed some of the things that would need to be changed for it to be eligible.

https://github.com/TeamNewPipe/NewPipe/issues/9559#issuecomment-1362107055

Also, please don't reach out to developers about Accrescent right now. It's in alpha, and gated behind a whitelist. Once it's open to submission, its developer will make an announcement about it.

**Comment by guilamoff** [comment]
Ok thanks.
