### ISSUE TITLE
Youtube Login Feature

### ISSUE THREAD

**Issue by Lacipe** [polymorphicshade/NewPipe#34]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Hi!
I love your newpipe version with Sponsorblock. What do you think, would it be possible for you to implement youtube login? Guys from smarttubenext project have done it very well, but for Android TV.

The thing is....if newpipe gets a login feature, then I have 0 reason to root my samsung phone to install youtube vanced. This would be very very good, because that means I dont lose knox, which means I dont lose samsung pass, pay, secure folder and wont have to fight with magisk scripts for gpay. Therefore it'd be amazing if you could make it happen....the whole samsung community would very much appreciate it!

**Comment by polymorphicshade** [comment]
I see you checked the checkbox indicating that you didn't find any duplicates, but I don't think you searched well enough.

See here: https://github.com/polymorphicshade/NewPipe/issues/20

I do not plan on implementing something like this, for it goes completely against NewPipe's design.

What do you need a YouTube login for? Posting comments? Liking videos? Doing anything like that means that you query Google APIs using NewPipe to Google.

The entire point of NewPipe is to enjoy as much YouTube (and other online video content) as possible without letting Google how you use YouTube.
