### ISSUE TITLE
When I play a video on Newpipe X Sponsorblock the app stops me

### ISSUE THREAD

**Issue by MuerteRoja** [polymorphicshade/NewPipe#349]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

Go to Newpipe X Sponsorblock 
Play a video 
Turn off your mobile phone screen

### Expected behavior

Normally the video is supposed to play

### Actual behavior

When I find myself using the application a poster appears in which tells me that an error has been detected and automatically the video that was playing stops me, this error has already occurred more than once, Newpipe x Sponsorblock is an application that I use frequently for my sports training, I put on a music video, I turn off the screen of the mobile phone and while I am running the application stops me.

### Logs

{"user_action":"play stream","request":"Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=TgMh71joTy4","content_language":"es-","content_country":"VE","app_language":"es","service":"YouTube","package":"org.polymorphicshade.newpipe","version":"0.25.1","os":"Linux Android 12 - 31","time":"2023-08-02 12:13","exceptions":["com.google.android.exoplayer2.ExoPlaybackException: Source error\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:210)\n\tat android.os.Looper.loop(Looper.java:299)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)\n\tat com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)\n\tat com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)\n\tat com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)\n\tat com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)\n\tat com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)\n\tat java.lang.Thread.run(Thread.java:1012)\n"],"user_comment":""}

### Affected Android/Custom ROM version

Android 12 MIUI 13

### Affected device model

Xiaomi Redmi 9

**Comment by Kurasami** [comment]
Fix is here but the dev needs to implement it. Pretty sure it was just patched on the upstream 2 days ago.

https://stackoverflow.com/questions/69040127/error-code-io-bad-http-status-exoplayer-android

**Comment by ghost** [comment]
> Fix is here but the dev needs to implement it. Pretty sure it was just patched on the upstream 2 days ago.

If true, then be patient and wait for the change to come downstream.

**Comment by Kurasami** [comment]
> > Fix is here but the dev needs to implement it. Pretty sure it was just patched on the upstream 2 days ago.
> 
> If true, then be patient and wait for the change to come downstream.

I was merely stating a fact dude for others who come across this, that it is fixed, we're just waiting for it to be pushed here too. Both you and @atemu are 🤡s.

@MuerteRoja Please test the latest version released today (0.25.2) and if it fixes the issue, close this ticket.

**Comment by MuerteRoja** [comment]
Yes, now the application in question works normally, thank you very much
