### ISSUE TITLE
Is this dead? Not a single commit since April? 

### ISSUE THREAD

**Issue by Kurasami** [polymorphicshade/NewPipe#350]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

Videos crash or stop playing for a variety of reasons.

Sometimes with an error pop-up, sometimes without.

Is there any chance of an update? There's been a lot of upstream changes lately.

Just curious if this is still being worked on and what the release schedule is like. It's crashing now on 1 out of 2 videos. 

### Affected Android/Custom ROM version

Android 13

**Comment by Kurasami** [comment]
Btw before anyone rages at me. I think basically all these errors have just been fixed via the upstream 0.25.2 version that released 2 days ago:

https://github.com/TeamNewPipe/NewPipe/issues/10284

So likely all we'd need is an upstream pull and merge to get us working again.

**Comment by Atemu** [comment]
0.25.2 isn't even out yet. WTH are you talking about? The newest upstream release is 0.25.1 and that's also the newest release here.

When 0.25.2 actually releases, expect an update no sooner than a few days later. People have lives.

**Comment by ghost** [comment]
Upstream releases infrequently and doesn't like being asked for releases. Last upstream release was in April.
So that's why there hasn't been a sync with upstream master since April.

**Comment by Kurasami** [comment]
> 0.25.2 isn't even out yet. WTH are you talking about? The newest upstream release is 0.25.1 and that's also the newest release here.
> 
> When 0.25.2 actually releases, expect an update no sooner than a few days later. People have lives.

Calm down. This isn't Reddit.

**Comment by SageSystems** [comment]
0.25.2 is now officially released on the main newpipe repo.

**Comment by shuvashish76** [comment]
https://github.com/polymorphicshade/NewPipe/releases/tag/v0.25.2

**Comment by Kurasami** [comment]
> 0.25.2 isn't even out yet. WTH are you talking about? The newest upstream release is 0.25.1 and that's also the newest release here.



> 0.25.2 is now officially released on the main newpipe repo.

It was 2 days ago when I commented 🗡️ https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.25.2

But apparently some people can't read and think being unnecessarily aggressive is the same as having a personality.

Anyway let's cross our fingers that this is fixed with the upstreams changes. The video errors were getting worse and worse 😔.

I'll close this in the meantime
