### ISSUE TITLE
Sponsorblock didn't not block unnecessary segment 

### ISSUE THREAD

**Issue by GreenMystic** [polymorphicshade/NewPipe#352]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2 and previous version

### Steps to reproduce the bug

1. open Newpipe X Sponsorblock
2. Go to setting enable all sponsorblock segment skip
3. open video that have unnecesary segment
4. sponsorblock not working

### Expected behavior

it's should working 

### Actual behavior

currently not working 

### Screenshots/Screen recordings

<img alt="IMG_20230805_122652_344" src="https://github.com/polymorphicshade/NewPipe/assets/136427398/1ea75d15-841b-46d0-b37f-464c69f9f51b" width=270 />
<img alt="IMG_20230805_122653_088" src="https://github.com/polymorphicshade/NewPipe/assets/136427398/cd5e95e1-8295-4422-803f-f54e83a2b701" width=270 />

### Affected Android/Custom ROM version

Android 11 R

### Affected device model

RMX 3265

### Additional information
• for troubleshooting i always try to do clean install and reproduce issues
• based on my testing sponsorblock only work on revanced other app like newpipe libretube won't work no matter how many i try
• app didn't crash so no log provided i only provide screenshot

**Comment by Atemu** [comment]
Just to make this clear, this video has sponsorblock segments in other apps/the browser add-on?

**Comment by 825i** [comment]
> Just to make this clear, this video has sponsorblock segments in other apps/the browser add-on?

From his screenshot it shows there is a segment (in blue) at the end. Youtube.com from the browser also shows this:

![Screenshot 2023-08-05 142046](https://github.com/polymorphicshade/NewPipe/assets/58630825/13eb5b6d-1014-4861-83b4-84bfdf71ca1b)

That said, it skipped for me at the end on 0.25.2. It's likely he doesn't have the API link set correctly.

**Comment by GreenMystic** [comment]
problem it's semi solved for now i think it's came from server bcs:
• sometime detect segment sometime not
• sometime work in other app sometime not

> > Just to make this clear, this video has sponsorblock segments in other apps/the browser add-on?
> 
> From his screenshot it shows there is a segment (in blue) at the end. Youtube.com from the browser also shows this:
> 
> ![Screenshot 2023-08-05 142046](https://user-images.githubusercontent.com/58630825/258581251-13eb5b6d-1014-4861-83b4-84bfdf71ca1b.png)
> 
> That said, it skipped for me at the end on 0.25.2. It's likely he doesn't have the API link set correctly.

also i enter them correctly sir to make sure i click on ? mark and choose use official :-) 
<img alt="Screenshot_20230806-095608" src="https://github.com/polymorphicshade/NewPipe/assets/136427398/408465c3-6afc-4bbc-8102-af2f267830e5" width=270 />
