### ISSUE TITLE
Add YouTube and Facebook login support to make a distinct app

### ISSUE THREAD

**Issue by SameenAhnaf** [polymorphicshade/NewPipe#36]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

SkipPipe (I know the name still depends, but I like calling this name) is an amazing fork. However, there should be a good reason why everyone should use SkipPipe instead of Newpipe. Only, skipping sponsor ads can't compell most Newpipe users.

I know, this kills the main design of Newpipe. But both "Auto backup" and "Annonimity" should be appreciated. Unless, the app will become just an ad blocker browser.

Facebook is way too diverse. So, it could be kept web version for this moment. Facebook videos should also get downloaded with the automatically detected title. Many browsers can download Facebook videos but title needs to be typed. Videos should be downloaded in audio format as well.

**Comment by polymorphicshade** [comment]
As I mentioned in previous issues like this, I will not be implementing any kind of YouTube login functionality. If you want features that come with a YouTube login, just use YouTube Vanced.

As for Facebook videos, if I remember correctly, don't you need a Facebook login to watch anything on Facebook? I haven't used Facebook in years so I'm out of the loop.

Nonetheless, I most definitely will not implement any kind of Facebook login functionality. In my opinion, nothing ruins an app's integrity more than adding anything Facebook-related. Facebook as a company is one of the worse things on this planet, and the less people use it the better.

**Comment by SameenAhnaf** [comment]
> As I mentioned in previous issues like this, I will not be implementing any kind of YouTube login functionality. If you want features that come with a YouTube login, just use YouTube Vanced.
> 
> As for Facebook videos, if I remember correctly, don't you need a Facebook login to watch anything on Facebook? I haven't used Facebook in years so I'm out of the loop.
> 
> Nonetheless, I most definitely will not implement any kind of Facebook login functionality. In my opinion, nothing ruins an app's integrity more than adding anything Facebook-related. Facebook as a company is one of the worse things on this planet, and the less people use it the better.

Fine! Mr. Ad blocker.

**Comment by SameenAhnaf** [comment]
> As I mentioned in previous issues like this, I will not be implementing any kind of YouTube login functionality. If you want features that come with a YouTube login, just use YouTube Vanced.
> 
> As for Facebook videos, if I remember correctly, don't you need a Facebook login to watch anything on Facebook? I haven't used Facebook in years so I'm out of the loop.
> 
> Nonetheless, I most definitely will not implement any kind of Facebook login functionality. In my opinion, nothing ruins an app's integrity more than adding anything Facebook-related. Facebook as a company is one of the worse things on this planet, and the less people use it the better.

I was talking about login functionality for both Facebook and YouTube. Please read my issue for both Facebook and YouTube. You might think "Facebook is for fun". But you never know others' needs. My teacher uploads his classes on Facebook.
