### ISSUE TITLE
Add the option to see replies on comments

### ISSUE THREAD

**Issue by mrkrabs206** [polymorphicshade/NewPipe#364]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

For this new feature, there will be a drop-down for replies on all comments, and when tapping on that, it will show the replies. Why no one did that feature? Please do it.

### Why do you want this feature?

I really want this to see replies on every comment possible!! Just do it

### Why ist the feature relevant to this fork?

Relevant to comments

### Additional information

Nothing

**Comment by mrkrabs206** [comment]
I just need it

**Comment by mrkrabs206** [comment]
Hello!!!!

**Comment by thanhminhmr** [comment]
This feature is already requested on the upstream repository (https://github.com/TeamNewPipe/NewPipe/issues/2277).
And please remember that this is an open source project, so if you really want a feature as soon as possible, do it yourself or pay someone to do it for you.
