### ISSUE TITLE
Back Button is Pausing the Video When in full screen

### ISSUE THREAD

**Issue by Raul1198** [polymorphicshade/NewPipe#42]
### Checklist

- [x] I am using the latest version - v0.20.10 R5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play a video
2. go to full screen by pressing the full screen button at the corner( you must have enabled Disable Tablet UI under Extras)

3.  press back button to go back in portrait playing video 

### Actual behavior

the video pauses upon pressing the back button instead of keep playing when left from landscape mode

### Expected behavior

the video should have continued from when it was left in landscape mode

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/29801315/109965570-23013900-7d15-11eb-945e-6ff2701748f5.mp4

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: Redmi K20 Pro

**Comment by polymorphicshade** [comment]
This should be fixed in the [latest release](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.20.11_r2).

**Comment by Raul1198** [comment]
Thanks
