### ISSUE TITLE
11 more features for "Long press on playlist"

### ISSUE THREAD

**Issue by SameenAhnaf** [polymorphicshade/NewPipe#46]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Currently, only "Remove" option is available for long press on playlist which is just boring. I am not in favour of quick shortcuts or playlists as that will make the UI too overcrowded. Rather, following options should be implemented as well.

1. Bookmark: Only for others' playlists

2. Allow self edit: Sometimes, we save others' playlists but need to add or don't need some certain videos. Often, the title or video arrangement is not up to our needs. Creating a completely new playlist just to organise a few videos is a hassle.
In such cases, allowing self edit will immensely help us.This editing the way should be as editing own playlist. "Allow self edit" option should be accessed from three dots button. Then, it should turn into an own playlist. A confirmation message might appear. I don't find it necessary.
However, ability to revert back to original playlist and access to the original playlist creator channel will be really great.
A separate section called "Created playlists" for all types of playlists modified and created by the user "Add to created playlist" option in three dots menu on every bookmarked playlist can be included.
If a user wants to revert back or access, he can do that from "Bookmarked playlists". If a user wants to have self control or edit by his own, he can do that from "Created playlists". If a user doesn't want to get overcrowded with too many similar playlists, he can remove the bookmark from others' playlist as well.
An option "Keep original playlist while self editing" option can be added if a user wants to keep or delete original playlist and access the creator channel.
Another option "Always name self-edited playlist by the original name" option in the settings can be added too. If enabled, a new rename popup won't appear. If disabled, a new popup will ask for renaming the self-edited playlist.

3. Categorise: There's no way to sort and categorise playlists properly. Only creation time sorting is available. Following sorting options should be included too.
A. Title (Alphabetical)
B. Total Video number
C. Fully played video number
D. Partially and fully played video number
E. Not played video number
F. Played time
G. Left time
(Suppose, two playlists have two and three hours of videos respectively. Both playlists are played for one hour. In terms of played time, they are the same. But in terms of left time, they are not. That's why, "Played time" & "Left time" should be separate sorting options)
H. Total Length
I. Watched length
J. Left length
All sorting options should have ascending and descending order option.

One more thing, categorising playlists under a name will be awesome. Playlist categories should be swiped from left to right just like subscription category. An option to add "a playlist category" on home page should be available. Seperate sorting option for every single category will be appreciated.
One more thing, while accessing "Bookmarked Playlists" tab, playlists should still stay categorised unlike subscription category. Plus, playlist sorting should appear under playlist category tiles. Just like subscription category tile, playlist categories should have the ability to be edited on a playlist category tile.
Another great thing to have is to hide a category by clicking on the title. In this way, certain playlists can be hidden if they seem to be distracting while working.
There should be a "Feed Update Button" while accessing playlist category tile (just like subscription category tile) to see if new videos added in playlists.
Playlist categories should appear in alphabetical order just like subscriptions. However, playlist category tiles might be arranged according to recently created.
Subscriptions are not as complex as playlists. That's why, subscriptions don't require such a huge management. Alphabetical sorting is enough for channels.

4. Start playing: All videos will start playing in full screen

5. Start playing with video info

6. Start playing in the background

7. Start playing in popup

8. Download: Download the full playlist (Downloading playlist and enqeued list should have options in #5657)

9. Merge: A new popup should appear which will have upper and lower menu. The lower menu should show bookmarked and created playlists. The upper menu should show the playlists to be merged. Playlists should appear from lower menu to upper menu by clicking on them once. The playlists in upper menu should be rearrangable and removable (just videos on enqeued list). Clicking on "OK" will finish merging and a new popup ask for saving previous playlists. A checkbox for "Don't show this again" can be added to always save or delete playlists. Then, a new popup will appear for asking new playlists' name.

10. Enqeue: The whole playlist will be enqeued

11. Set a playlist thumbnail: All video titles and thumbnails will appear. Selecting a video title should set that video thumbnail as the default playlist thumbnail.

Split playlist option is not required as the playlist has to be open ultimately. Bulk selection gestures should be added as soon as possible for easy splitting.

#### How will you/everyone benefit from this feature?

Managing playlists will be a breeze.

**Comment by polymorphicshade** [comment]
This would be better requested over at the official NewPipe repo.
