### ISSUE TITLE
Allow renaming export file 

### ISSUE THREAD

**Issue by SameenAhnaf** [polymorphicshade/NewPipe#47]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Could you please add an option to rename the backup file while exporting? It creates zip files with a really awkward and new name every single time which is quite hard for users to understand. Plus, renaming the file will allow users to replace previous file easily showing a popup "A file with the same name already exists.". Three options can be kept as reply "Rename again", "Replace file" and "Cancel exporting"

**Comment by polymorphicshade** [comment]
This would be better requested over at the official NewPipe repo.
