### ISSUE TITLE
Give an ability to add another video streaming service

### ISSUE THREAD

**Issue by Joe23232** [polymorphicshade/NewPipe#50]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

It would be nice if we can add more video streaming services of our own choice.

#### How will you/everyone benefit from this feature?

YouTube has been banning/demonetizing people's videos, even over a [Duck video](https://www.youtube.com/watch?v=pFCUGemAy6Y&t=1s) that only literally shows a video of a duck and nothing more, and more and more content creators are forced to move over to alternatives. I was hoping if we can just some how add an alternative by copying and pasting the alternative video streaming platform into NewPipe.

**Comment by multichoyce** [comment]
Use VLC

**Comment by Joe23232** [comment]
> Use VLC

How does it support the ability to add other videos please explain?

**Comment by multichoyce** [comment]
@Joe23232 copying and pasting

**Comment by Joe23232** [comment]
You mean I can watch online videos?

**Comment by multichoyce** [comment]
@Joe23232 https://github.com/videolan/vlc

**Comment by polymorphicshade** [comment]
This would be better suggested over at the official NewPipe repo.

**Comment by Joe23232** [comment]
> see this mpv version: [mpv-android/mpv-android#58](https://github.com/mpv-android/mpv-android/pull/58)

Is this supported on Android?

**Comment by Joe23232** [comment]
> This would be better suggested over at the official NewPipe repo.

It has been suggested over NewPipe but those retards actually support censorship. That is why I came to you guys. Because they want to support censorship.

https://github.com/TeamNewPipe/NewPipeExtractor/pull/325#issuecomment-626801193

Take a look at this disgusting comment they have made why they can't add BitChute.

Honestly what is the difference in using New Pipe vs YouTube if they both support complete censorship?

**Comment by polymorphicshade** [comment]
@Joe23232 I see where they are coming from, but I agree they shouldn't restrict the access of information based on moral grounds.
I'm not opposed to having something like BitChute on my fork, but I do not plan on modifying the extractor.

For me, the scope of this fork is adding SponsorBlock and a few more small or complimentary tweaks. Adding the ability to add a user-defined streaming service is a much larger feature and I don't plan on putting in the effort for that.

If someone else wants to submit a pull request with this kind of feature I'm more than happy to merge it in my fork.

**Comment by Joe23232** [comment]
Glad to see at least you are better :)
