### ISSUE TITLE
Crashing if tried to download any video

### ISSUE THREAD

**Issue by mizzunet** [polymorphicshade/NewPipe#51]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Version 0.20.11_r2
1. Search for any video
2. Open it
3. Press Download button

### Actual behaviour

NewPipe stops working then and app is even opening, it's just crashing unless if I clear its data.

### Expected behavior

Show downloading confirmation and start downloading

### Screenshots/Screen recordings

http://transfer.sh/EW2Zb/screen-20210323-231936.mp4

### Logs

http://transfer.sh/Cy9sl/logs-2021-03-23-23-13-12.zip

### Device info

 - Android version/Custom ROM version: Revenge OS 4.0
 - Device model: OnePlus 5

**Comment by multichoyce** [comment]
Is it working fine on the upstream version?

**Comment by mizzunet** [comment]
> Is it working fine on the upstream version?

The original NewPipe? havn't tried, let me

**Comment by mizzunet** [comment]
Yes, it works on latest upstream version

**Comment by multichoyce** [comment]
@mizzunet are the settings the same in both apps? Seems to be working fine on my end

**Comment by mizzunet** [comment]
> @mizzunet are the settings the same in both apps? Seems to be working fine on my end

Yes, it happens on both data cleared, so at default settings. Maybe it is device side, but upstream works

**Comment by multichoyce** [comment]
@mizzunet strange indeed, hopefully logs will have something useful. I'll have a go on a different rom and see if I'm able to replicate it

**Comment by mizzunet** [comment]
> @mizzunet strange indeed, hopefully logs will have something useful. I'll have a go on a different rom and see if I'm able to replicate it

🤗

**Comment by polymorphicshade** [comment]
@mizzunet try the [latest release](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.21.0) and see if you still have issue downloading videos.

**Comment by mizzunet** [comment]
> @mizzunet try the [latest release](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.21.0) and see if you still have issue downloading videos.

No problem on latest version, thanks :)
