### ISSUE TITLE
[IMPORTANT] Please update to 0.21.0 ASAP

### ISSUE THREAD

**Issue by SameenAhnaf** [polymorphicshade/NewPipe#53]
### Checklist

- [x] I am using the latest version- 0.20.11_r2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

It has been over 3 days since new version of Newpipe is released. Please update the fork as well.

### Actual behaviour

Newpipe Sponsorblock is still stuck to 0.20.10

### Expected behavior

This fork should be updated within a few hours when a new version arrives.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by 07416** [comment]
Are there known playback issues?

https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.21.0

**Comment by polymorphicshade** [comment]
Been very busy with work. I ran into a large issue while merging the latest changes the day 0.21.0 released and I have not had time to troubleshoot it. However I should be able to get everything fixed sometime this weekend.

Also...
"This fork should be updated within a few hours when a new version arrives"
This assumes I have no other priorities in my life 😉

**Comment by SameenAhnaf** [comment]
@polymorphicshade I am really sorry. I saw B0pol and TobiGr commenting here. Not sure if they are contributing by uploading apk though.

All my teachers upload classes on YouTube. You know the weird nature of YouTube webpages. It's frustrating to stay backdated. .

**Comment by SameenAhnaf** [comment]
@07416 No, I found no new issue.

**Comment by SameenAhnaf** [comment]
@polymorphicshade I am really sorry. I saw B0pol and TobiGr commenting here. Not sure if they are contributing by uploading apk though. You know the weird nature of YouTube webpages. It's frustrating to stay backdated.

**Comment by CalAlaera** [comment]
FYI: there are now playback issues, every video I've tried isn't playing, also the vast majority of subscriptions (150/152) aren't updating.

**Comment by 07416** [comment]
^I also had playback issues with audio starting from yesterday or earlier, but didn't research and switched to the main branch for now.

**Comment by rodrigoswz** [comment]
Dude, this is probably the most disrespectful "issue" I've ever seen...

If you're in such a hurry, fork latest NewPipe yourself, merge with success SB patches and open a PR here.

The opensource community would appreciate it ✌️

**Comment by polymorphicshade** [comment]
Give the [latest release](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.21.0) a try. Hopefully I didn't break anything...
