### ISSUE TITLE
Can't block sponsors from certain channels

### ISSUE THREAD

**Issue by SameenAhnaf** [polymorphicshade/NewPipe#54]
### Checklist

- [x] I am using the latest version - 0.21.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

This app blocks most sponsors amazingly. However, that's not the case with many channels. I can't skip unwanted introes, sponsors (of the creators' products), endcards etc. Here are the links of the channels.

Reallife English: https://www.youtube.com/channel/UC9d2mNoH8coSqtnotE81Tww
Learn English with TV series:
https://www.youtube.com/channel/UCKgpamMlm872zkGDcBJHYDg

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by ralphocdol** [comment]
I'm no expert in SponsorBlock so correct me if I'm wrong, but I believe that someone from the community (you, me, everyone using it) have to create a segment to be skipped and send it for everyone to use.

**Comment by lawson85** [comment]
On a desktop or any other compatible device/browser you add a segment which you believe to be spam. After I think 1 hour, the database for NewPipe updates and skips for you. More info here: https://sponsor.ajay.app/

The more you submit the higher you get on the leader board as well.
