### ISSUE TITLE
Add "Contribute segment" button for Sponsorblock in secondary controls on video info.

### ISSUE THREAD

**Issue by SameenAhnaf** [polymorphicshade/NewPipe#57]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

"Record segment" could potentially help us contribute directly from the app. Smartphone is one of the most used devices for streaming. It will be really helpful as it is easier to contribute while streaming especially for Newpipe Sponsorblock users. Main player seek bar should also be shown all the time while recording a segment.

Single tap on "Contribute segment" will start recording the segment. Single tap again on the button will pause recording. Exiting from main player once or long press on on the button should show "Contribution popup" (with all segments) before opening mini player. Main or mini player will stay paused at this moment.

Top menu: The "Contribute popup" will show all the segments for confirmation. Drop-down menu will be kept on the left of each position for choosing sponsor category.
Positions will be mentioned on the centre. Single tap on "Position" will let the user edit the segment. Long press on "Position" should let user play that single segment
Middle menu: A "Play" icon for playing all segments on right. All segments should get enqueued separately from the beginning. A resolution drop-down menu for playing segments should be kept on left. No matter which resolution is selected, video will play on background (audio) or popup (video). This resolution will apply for playing the single segments too. Previous resolution will appear for next contribution popup too.
Bottom row: "Submit" and "Cancel" will let the user submit positions and cancel the operation respectively.

No need to show confirmation popup after recording every single segment as that will interrupt the streaming experience. If a user needs to check his segments, he can do any time by long press on the button.

#### How will you/everyone benefit from this feature?

This will let the user contribute for Sponsorblock directly from the app.

**Comment by polymorphicshade** [comment]
@SameenAhnaf if you searched the list of issues, you'll see I do not plan on implementing SponsorBlock segment-submissions.

Perhaps I need to pin an issue or two...
