### ISSUE TITLE
SponsorBlock doesn't automatically skip sponsors at 0:00

### ISSUE THREAD

**Issue by ralphocdol** [polymorphicshade/NewPipe#59]
As the title says, when there's a blocked sponsor at the beginning of the video, it doesn't automatically skip

**Comment by Atemu** [comment]
How long is that sponsor? Got a link?  

Something I think is happening is that there's a little delay before a sponsor is skipped, so it might not really skip very short intro sections for example.

**Comment by HairyMilkshakes** [comment]
Here's an example: https://www.youtube.com/watch?v=7JttwV6XZ_I

Try viewing this video in mobile/tablet and it'll display the skip message while playing through the segment.

**Comment by PacoBell** [comment]
Yeah, here's another one that doesn't skip @ 0:00 properly:

https://www.youtube.com/watch?v=hjTmu5SzbME

**Comment by the-blank-x** [comment]
Here's yet another example (sponsor lasts one minute): https://www.youtube.com/watch?v=IMrqAEwEpNE

**Comment by SameenAhnaf** [comment]
On my phone, this problem persists in a really weird way. Typically, you can't seek position within the sponsored segment. However, it's possible for segments starting from 0:00.

The problem doesn't persist in some cases.
1. The videos you have opened once (even if history is disabled or mini player is closed)
2. If you play the segment completely
3. If you seek position after the sponsored segment at least for once.

However, it can recognize the same sponsors later absolutely fine. Sorry for poor quality. I had to cover the file size limit.


https://user-images.githubusercontent.com/79245641/116860081-d194fd80-ac22-11eb-9d8c-c07d99692ef4.mp4


>so it might not really skip very short intro sections for example.

Yes, short lag like two seconds is acceptable. But the app neither skips 1 minute long sponsor at the beginning for now.

**Comment by SuperMeepBoy** [comment]
Don't know if you need more examples but this song of BTS https://www.youtube.com/watch?v=gdZLi9oWNZg does start with a little introduction that starts at 00:00. I enabled skip "non-music" part of musics and when I play it I get the notification which said a non-music part has been skipped but the non-music part is still played.
