### ISSUE TITLE
Delay when loading or turning screen off

### ISSUE THREAD

**Issue by pokegamer5547** [polymorphicshade/NewPipe#64]
## checklist

- [x] I am using the latest version -0.21.3  
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Load a video or turn the screen off or on.

## Actual behaviour
Unlike original Newpipe, there is a delay when video or audio loads with sponsorblock build. It's quite noticable when compared side by me. Newpipe reloads audio or video when screen is off/turned on when off within 1 seconds but sponsorblock release takes 3 seconds. It happening during even in mid video so it's not probably not about getting segments.

### Device info

 - Android version/Custom ROM version: android 10, miui 12
 - Device model: redmi note 9 pro max

**Comment by polymorphicshade** [comment]
Try doing this with the latest version of my fork. If you still see a problem I'll re-open this issue.
