### ISSUE TITLE
Sponsorblock now working

### ISSUE THREAD

**Issue by tegutistgut** [polymorphicshade/NewPipe#69]
Newest version? Yes!
Device: Samsung Galaxy A51, Android 11, OneUI 3.1, newest security patch and Google Play systemupdate.

I dont know what i am doing wrong. Im using the official sponsorblock api and i activated everything necessary. But newpipe does not show me the sponsor-parts.

YT-Vanced's sponsorblock works, and the desktop addon too.

I cant be the only one?

**Comment by Atemu** [comment]
It's working for me. Perhaps clear the cache?

Are you sure the video you're trying has Sponsorblock segments?

Have you made sure Sponsorblock isn't disabled temporarily via the button in the player?

Try turning it off and on again. (No, seriously.)

**Comment by tegutistgut** [comment]
> It's working for me. Perhaps clear the cache?

Didnt work

> Are you sure the video you're trying has Sponsorblock segments?

Yes its a LTT video, that has sponsorblocj segments on vanced and the addon.

> Have you made sure Sponsorblock isn't disabled temporarily via the button in the player?

There is no button in the player. (Not even in previous versions)

> Try turning it off and on again. (No, seriously.)

Didnt work

**Comment by polymorphicshade** [comment]
Closed as I do not have enough information to investigate this.
@tegutistgut Give the latest version a try and see if you are still not seeing marked sponsor segments.

**Comment by tegutistgut** [comment]
Its still not working. Even after the newest version.
And i really don't know what I'm doing wrong.

I activate it by using the "original api link" button and activating the color segments but it doesn't shows up

**Comment by Atemu** [comment]
Try resetting the app. Not much we can do to help when we can't repro the issue.
