### ISSUE TITLE
android.os.AsyncTask Deprecation

### ISSUE THREAD

**Issue by jimman2003** [polymorphicshade/NewPipe#7]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
android.os.AsyncTask is deprecated.. The android docs recommend migrating to the standard java.util.concurrent or Kotlin concurrency utilities...Similar api it seems..

#### Is your feature request related to a problem? Please describe it
Minor problem, just a deprecation

#### Additional context
[Your code](https://github.com/polymorphicshade/NewPipe/blob/86b324467d4b0cef03ea62690ae6464d42b08d19/app/src/main/java/org/schabi/newpipe/SponsorBlockApiTask.java#L6)
See [android docs on AsyncTask]( https://developer.android.com/reference/android/os/AsyncTask)

#### How will you/everyone benefit from this feature?
Newer code,yay!

**Comment by polymorphicshade** [comment]
This should be fixed in release [v0.20.6](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.20.6) (see commit cbcb0f7).
