### ISSUE TITLE
What's the API url ?

### ISSUE THREAD

**Issue by stemy2** [polymorphicshade/NewPipe#70]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour
The "API Url" is empty, so sponsorblock can't work, but i have no idea of what url i'm supposed to enter.

**Comment by Atemu** [comment]
Tap the question mark in the popup.
