### ISSUE TITLE
Option revert back to exoplayer v1

### ISSUE THREAD

**Issue by NSTAdventure** [polymorphicshade/NewPipe#71]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### How will you/everyone benefit from this feature?
this feature will make newpipe supported for all devices included mine i use realme 5i that doesn't support exoplayer v2 unfortunately

**Comment by NSTAdventure** [comment]
note:
trying to create new issues will never help you 
it's looks like dev reject my idea on main repo :( this why i create issues on forked one instead of main repo

**Comment by Atemu** [comment]
Legacy device support is way out of scope for this project.

**Comment by NSTAdventure** [comment]
> Legacy device support is way out of scope for this project.

?

**Comment by PoorPocketsMcNewHold** [comment]
Meaning this is a no.
This fork won't create legacy Newpipe builds with the older ExoPlayer, nor contain it in the newer releases.

**Comment by NSTAdventure** [comment]
:( my devices lagging when use v2

**Comment by polymorphicshade** [comment]
Closed as I have no plans on supporting a legacy version of the ExoPlayer.

**Comment by NSTAdventure** [comment]
> Closed as I have no plans on supporting a legacy version of the ExoPlayer.

But how do i overcome this issues? My devices lagging if try to use exoplayer v2

**Comment by PoorPocketsMcNewHold** [comment]
Develop your own fork, or just use other applications. NewPipe isn't for your device. Try even website interfaces like invidious, piped & viewtube instead on it.

**Comment by Atemu** [comment]
Also try using the h264 streams (there's a setting in NP); they look worse but have better compatibility.

**Comment by NSTAdventure** [comment]
> Also try using the h264 streams (there's a setting in NP); they look worse but have better compatibility.

Give me tutorial pls?

**Comment by Atemu** [comment]
"Default video format" in the settings.

**Comment by NSTAdventure** [comment]
> "Default video format" in the settings.

Thanks 

EDIT:
Nvm newpipe are good even with exoplayer v2
But why yt lag?something wrong with yt nowadays

Btw do f droid have repo of newpipe with sponsorblock? I didn't remember i add it because i can update this version from f droid too :-/
