### ISSUE TITLE
Support to contribute to sopnserblock

### ISSUE THREAD

**Issue by Thewisem** [polymorphicshade/NewPipe#74]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Is your feature request related to a problem? Please describe it

I want to remove a segment but there is no way to do so.

#### How will you/everyone benefit from this feature?

This will help for people who want to contribute to the project. Or for people who want to remove specific segments

**Comment by Atemu** [comment]
It's already been discussed that this isn't going to happen.

Such functionality was there in the initial stages but it's been deemed too imprecise on mobile.

**Comment by SameenAhnaf** [comment]
See: https://github.com/polymorphicshade/NewPipe/issues/15#issuecomment-743357509

**Comment by polymorphicshade** [comment]
Closed, see the pinned issue.
