### ISSUE TITLE
MacroDroid and Tasker support

### ISSUE THREAD

**Issue by lawson85** [polymorphicshade/NewPipe#75]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I had a look at the manifest file to find intents however, I cannot figure them out. 
Also, I asked upstream last year and had no response

#### Is your feature request related to a problem? Please describe it

Not a problem actually

#### Additional context

Here is how to add this feature: https://tasker.joaoapps.com/plugins-intro.html
and https://developer.android.com/guide/topics/ui/shortcuts/creating-shortcuts

#### How will you/everyone benefit from this feature?

This would make this version of NP more attractive than the original as well

**Comment by Atemu** [comment]
Unless this is somehow a controversial feature upstream or related to sponsors, ads or other kinds of propaganda, I fail to see how this is relevant here.  
This needs be solved upstream and if nobody's willing to do it for you, that simply means there isn't much interest.

I'm sure if you were to send a PR upstream, it'd get accepted.

**Comment by polymorphicshade** [comment]
Closed as this would be better suited for an upstream request.
