### ISSUE TITLE
Option to hide sponsors in seel bar

### ISSUE THREAD

**Issue by HTSamurai** [polymorphicshade/NewPipe#78]
NewPipe with sponsor block is great, but what if there was an option to subtract the selected categories from the seek bar and remove it from the video length? Of course, this would be optional, but this could make it as if sponsors just cease to exist. I don't like all the colours in the bar, and if these parts won't be shown, why show that in the watch timer and the video length? 

This is why I propose an option to just hide all of that as if it never existed be added.

**Comment by polymorphicshade** [comment]
I have no plans on working on something like this, but if someone else implements this I'll be happy to merge in their changes.
