### ISSUE TITLE
Add link to the fork on About page

### ISSUE THREAD

**Issue by repparw** [polymorphicshade/NewPipe#79]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think you should edit the "Contribute" link in the About menu so it links to this repo instead of TeamNewPipe/NewPipe, or at least add another link specific to this repo, so people could get to this repo from there

#### Additional context

![Screenshot_20210717-000418564](https://user-images.githubusercontent.com/45952970/126023498-b006e16d-ae74-4104-82aa-b8afb501f9dd.jpg)

**Comment by m-p-3** [comment]
I believe that would be changed through https://github.com/polymorphicshade/NewPipe/blob/sponsorblock/app/src/main/res/values/strings.xml#L422, but I don't have the technical knowledge to compile my own version to submit a proper PR.

**Comment by polymorphicshade** [comment]
This is fixed in the latest release.
