### ISSUE TITLE
0.21.6 & 0.21.7 releases?

### ISSUE THREAD

**Issue by infinitewaveparticle** [polymorphicshade/NewPipe#80]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I am simply pointing out that two releases of the upstream app have been made without any updates to this fork. polymorphicshade, are you on vacation? No problem if you are!

#### Is your feature request related to a problem? Please describe it

The new releases fix and enhance several things, so I would say the problems are all the fixes in 0.21.6 & 0.21.7.

#### How will you/everyone benefit from this feature?

Users will have access to the most up-to-date features and bug fixes as well as SponsorBlock.

**Comment by Atemu** [comment]
Should be coming as soon as someone resolves all the merge conflicts.

**Comment by xdIceBear** [comment]
Yup need this
