### ISSUE TITLE
Error with comments

### ISSUE THREAD

**Issue by stemy2** [polymorphicshade/NewPipe#81]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to any video
2. Show the comments

### Actual behavior
Instead if the expected comments, the message "sorry, something wrong happened", with the buttons " report" and "retry". Sometimes "retry" fixes it but often, it doesn't.

### Expected behavior
The comments.

### Logs

Rapport d’erreur - {"user_action":"requested comments","request":"Start loading: https://www.youtube.com/watch?v=rPNSnHhqTYo","content_language":"fr-BE","content_country":"BE","app_language":"fr_BE","service":"YouTube","package":"org.polymorphicshade.newpipe","version":"0.21.5","os":"Linux Android 8.1.0 - 27","time":"2021-07-25 22:11","exceptions":["org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json data for comments\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:100)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getInitialPage(YoutubeCommentsExtractor.java:55)\n\tat org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)\n\tat org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:40)\n\tat org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:154)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$60N_-UL7E5eaxFaFO1bZZmnfwM8.call(Unknown Source:4)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)\n\tat java.lang.Thread.run(Thread.java:764)\nCaused by: com.grack.nanojson.JsonParserException: Unexpected character: < on line 1, char 1\n\tat com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)\n\tat com.grack.nanojson.JsonTokener.advanceToToken(Unknown Source:118)\n\tat com.grack.nanojson.JsonParser.advanceToken(Unknown Source:12)\n\tat com.grack.nanojson.JsonParser.parse(Unknown Source:1)\n\tat com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:98)\n\t... 19 more\n"],"user_comment":""}

### Device info

 - Android version/Custom ROM version: 8.1
 - Device model: galaxy s7

**Comment by multichoyce** [comment]
Upstream has a similar issue open for comments, don't think it's specific to this fork

**Comment by polymorphicshade** [comment]
Closing this due to it not being related to my fork.
