### ISSUE TITLE
[Feature Request] Playlist shuffle

### ISSUE THREAD

**Issue by emmatebibyte** [polymorphicshade/NewPipe#85]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

There's not really an alternative other than choosing individual songs at random.

#### Is your feature request related to a problem? Please describe it

Self-explanatory.

#### Additional context

N/A

#### How will you/everyone benefit from this feature?

Anyone can shuffle playlists on the regular youtube app and site. Why not on this newpipe fork?

**Comment by Atemu** [comment]
Why did you report this here and not upstream?

**Comment by polymorphicshade** [comment]
This is better requested upstream. If they refuse to implement this for whatever reason, I'll consider it.
