### ISSUE TITLE
Add an option to create Sponsorblock accounts and add segments to videos like at YT Vanced.

### ISSUE THREAD

**Issue by d4f5409d** [polymorphicshade/NewPipe#87]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by polymorphicshade** [comment]
See the pinned issues.
