### ISSUE TITLE
Channel names' don't have icons

### ISSUE THREAD

**Issue by francois072** [polymorphicshade/NewPipe#88]
Channel names' don't have icons.
![Screenshot_20210808-211229](https://user-images.githubusercontent.com/64827815/128643209-a67095a5-01a9-4b15-9026-0fb95a421380.png)

**Comment by Atemu** [comment]
Can't reproduce this. Have you tried clearing the cache?

**Comment by francois072** [comment]
> Can't reproduce this. Have you tried clearing the cache?

Yes I tried that and I also cleared all the data and reinstalled.

**Comment by Atemu** [comment]
Couldn't repro this with a clean install either. Does the same happen in regular NP?

**Comment by francois072** [comment]
No on regular NP it's fine. I installed from Izzy via F-droid, but it also happned with version directly from github.

**Comment by Atemu** [comment]
That's odd. I assume you also cleared cache and/or data on regular NP? The images cached locally.

@polymorphicshade are you able to repro?

**Comment by francois072** [comment]
Yes a cache and data of regular NP was cleared since Mmy phone was factory reset and I only installed the sponsor block NP.

**Comment by Atemu** [comment]
Do you have other devices you could test this on or get access to an emulator? (Android Studio comes with one)

That way we can rule out the device as a factor. I have a hunch it might be your network; try via mobile data for example and try temporarily disabling ad blockers (i.e. DNS) and the like.

**Comment by polymorphicshade** [comment]
I've never been able to reproduce this, and I'm pretty sure this has nothing to do with my fork. I'll re-open this issue if @francois072 can prove this happens only with my fork and not upstream NewPipe.
