### ISSUE TITLE
use release  section 

### ISSUE THREAD

**Issue by MD77MD** [polymorphicshade/NewPipe#9]
Could you you put new versions in the release section.

![Screenshot_20201201-153951_Samsung Internet](https://user-images.githubusercontent.com/63132171/100742245-882e5100-33eb-11eb-83db-80d8da979dcd.jpg)

this way we can subscribe to your repository and -more importantly- get notified of new releases.

**Comment by polymorphicshade** [comment]
Done! See: https://github.com/polymorphicshade/NewPipe/releases
