### ISSUE TITLE
Keyboard takes Ages to Open

### ISSUE THREAD

**Issue by Halfmit** [polymorphicshade/NewPipe#92]
### Checklist

- ☑️ I am using the latest version - v0.21.8 w/ SponsorBlock 
- ☑️ I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- ☑️ I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- ☑️ This issue contains only one bug. I will open one issue for every bug report I want to file.

 ##Steps to reproduce the bug
1. Go to the app
2. Press on search icon
3. Wait for keyboard to open.

### Actual behavior
The keyboard should quickly show up so that I can search for the video I want to see. But Alas! I have to click ten times on the search bar. Wait for 10 seconds or so. Then keyboard appear. Frustrating when one is used to watching YouTube videos whole day.

### Expected behavior
Keyboard should show up as soon as I click on the search icon.

### Device info

 - Android version: 8.1.0 running on MIUI Global 11.0.2 | Stable
 - Device model: Redmi 5A

**Comment by Atemu** [comment]
Can't reproduce this on my end. Does it happen with a clean installation? Maybe try a different keyboard to rule that out as a factor?

Have you tried turning it off and on again? (Seriously)

**Comment by lawson85** [comment]
I get it sometimes but my keyboard is just slow. 

You could follow steps at dontkillmyapp.com for both NP and the keyboard apps. 

See if there's a performance mode on your device and Debloat with Universal Android Debloater. If these don't help maybe flash a custom ROM like Lineage OS.

**Comment by polymorphicshade** [comment]
I can't reproduce this issue in an emulator nor on my physical device. Please verify you do not see this behavior with the latest version of upstream NewPipe. If you can only reproduce this issue with my fork, I'll re-opn this issue.
