### ISSUE TITLE
Subscriptions.json not importing

### ISSUE THREAD

**Issue by Halfmit** [polymorphicshade/NewPipe#94]
### Checklist

- [x] I am using the latest version - 0.21.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

You would get the message 'Could not import Subscriptions. No such file/content source. (Yes I do have the json file downloaded from takeout of google.

### Expected behavior

It should have imported my YouTube subs.

### Device info

 - Android version/Custom ROM version:  Android 8.1.0 on MIUI Global 11.0.2
 - Device model: Redmi 5A

**Comment by Atemu** [comment]
Upstream issue: https://github.com/TeamNewPipe/NewPipe/issues/6757
