### ISSUE TITLE
NSFW video support

### ISSUE THREAD

**Issue by HairyMilkshakes** [polymorphicshade/NewPipe#98]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### Describe the feature you want

Support for age-restricted (NSFW) videos. For example: https://youtu.be/VmR7pEEpTJk viewed in the app won't load.

#### Is your feature request related to a problem? Please describe it

Yes, currently age-restricted videos are not supported.

#### How will you/everyone benefit from this feature?

We will be able to bypass and view age-restricted videos.

**Comment by Atemu** [comment]
What does this have to do with sponsorblock? Report this upstream.

**Comment by dariusjonda** [comment]
You can enable it yourself. 
Just go to settings - content - show restricted content

**Comment by Atemu** [comment]
As another user correctly noted (though they seem to have deleted their comment), there's a setting in NewPipe to control whether restricted videos should be loaded and shown that is disabled by default.

Working as intended.
